In [0]:
import pandas as pd
import io
import requests

In [0]:
url = "https://datasets.imdbws.com/name.basics.tsv.gz"
name_basics_df = pd.read_csv(url, compression='gzip', sep='\t')

name_basics_df.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0031983"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack,archive_footage","tt0037382,tt0075213,tt0117057,tt0038355"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"

In [0]:
url = "https://datasets.imdbws.com/title.basics.tsv.gz"
title_basics_df = pd.read_csv(url, compression='gzip', sep='\t')

title_basics_df.head()

<command-3511027810573584>:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  title_basics_df = pd.read_csv(url, compression='gzip', sep='\t')

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short

In [0]:

%sql SHOW DATABASES;

databaseName
bronze
default

In [0]:
%sql
-- Drop the database using IF EXISTS
-- DROP DATABASE CASCADE - deleta um database e suas tabelas 
DROP DATABASE IF EXISTS bronze CASCADE;

In [0]:
%sql CREATE DATABASE bronze;

In [0]:
%sql SHOW DATABASES;

databaseName
bronze
default

In [0]:
name_basics_spark_df = spark.createDataFrame(name_basics_df)
name_basics_spark_df.write.mode("overwrite").saveAsTable("bronze.name_basics")

In [0]:
title_basics_spark_df = spark.createDataFrame(title_basics_df)
title_basics_spark_df.write.mode("overwrite").saveAsTable("bronze.title_basics")

/databricks/spark/python/pyspark/sql/pandas/conversion.py:467: UserWarning: createDataFrame attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  Could not convert '0' with type str: tried to convert to int64
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)

In [0]:
%sql SELECT * FROM bronze.name_basics LIMIT 10

nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
nm0000001,Fred Astaire,1899,1987,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0031983"
nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack,archive_footage","tt0037382,tt0075213,tt0117057,tt0038355"
nm0000003,Brigitte Bardot,1934,\N,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
nm0000004,John Belushi,1949,1982,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"
nm0000006,Ingrid Bergman,1915,1982,"actress,producer,soundtrack","tt0034583,tt0038109,tt0036855,tt0038787"
nm0000007,Humphrey Bogart,1899,1957,"actor,producer,miscellaneous","tt0034583,tt0043265,tt0037382,tt0033870"
nm0000008,Marlon Brando,1924,2004,"actor,director,writer","tt0078788,tt0068646,tt0047296,tt0070849"
nm0000009,Richard Burton,1925,1984,"actor,producer,director","tt0061184,tt0087803,tt0059749,tt0057877"
nm0000010,James Cagney,1899,1986,"actor,director,producer","tt0029870,tt0031867,tt0042041,tt0034236"

In [0]:
%sql SELECT * FROM bronze.title_basics LIMIT 10

tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
tt0000003,short,Poor Pierrot,Pauvre Pierrot,0,1892,\N,5,"Animation,Comedy,Romance"
tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,Short
tt0000006,short,Chinese Opium Den,Chinese Opium Den,0,1894,\N,1,Short
tt0000007,short,Corbett and Courtney Before the Kinetograph,Corbett and Courtney Before the Kinetograph,0,1894,\N,1,"Short,Sport"
tt0000008,short,Edison Kinetoscopic Record of a Sneeze,Edison Kinetoscopic Record of a Sneeze,0,1894,\N,1,"Documentary,Short"
tt0000009,movie,Miss Jerry,Miss Jerry,0,1894,\N,45,Romance
tt0000010,short,Leaving the Factory,La sortie de l'usine Lumière à Lyon,0,1895,\N,1,"Documentary,Short"

In [0]:
%sql DROP DATABASE IF EXISTS silver CASCADE;

In [0]:
%sql CREATE DATABASE silver

In [0]:
from pyspark.sql.functions import explode
from pyspark.sql.functions import split

name_basics_titles_spark_df = name_basics_spark_df.select(name_basics_spark_df.nconst, name_basics_spark_df.primaryName, explode(split(name_basics_spark_df.knownForTitles, ',')).alias("tconst"))
name_basics_titles_spark_df.show(10)

+---------+---------------+---------+
|   nconst|    primaryName|   tconst|
+---------+---------------+---------+
|nm0000001|   Fred Astaire|tt0072308|
|nm0000001|   Fred Astaire|tt0050419|
|nm0000001|   Fred Astaire|tt0027125|
|nm0000001|   Fred Astaire|tt0031983|
|nm0000002|  Lauren Bacall|tt0037382|
|nm0000002|  Lauren Bacall|tt0075213|
|nm0000002|  Lauren Bacall|tt0117057|
|nm0000002|  Lauren Bacall|tt0038355|
|nm0000003|Brigitte Bardot|tt0057345|
|nm0000003|Brigitte Bardot|tt0049189|
+---------+---------------+---------+
only showing top 10 rows

In [0]:
name_basics_titles_spark_df.write.mode("overwrite").saveAsTable("silver.name_basics_titles")

In [0]:
%sql SELECT * FROM silver.name_basics_titles LIMIT 100

nconst,primaryName,tconst
nm0000001,Fred Astaire,tt0072308
nm0000001,Fred Astaire,tt0050419
nm0000001,Fred Astaire,tt0027125
nm0000001,Fred Astaire,tt0031983
nm0000002,Lauren Bacall,tt0037382
nm0000002,Lauren Bacall,tt0075213
nm0000002,Lauren Bacall,tt0117057
nm0000002,Lauren Bacall,tt0038355
nm0000003,Brigitte Bardot,tt0057345
nm0000003,Brigitte Bardot,tt0049189
nm0000003,Brigitte Bardot,tt0056404
nm0000003,Brigitte Bardot,tt0054452
nm0000004,John Belushi,tt0072562
nm0000004,John Belushi,tt0077975
nm0000004,John Belushi,tt0080455
nm0000004,John Belushi,tt0078723
nm0000005,Ingmar Bergman,tt0050986
nm0000005,Ingmar Bergman,tt0069467
nm0000005,Ingmar Bergman,tt0050976
nm0000005,Ingmar Bergman,tt0083922
nm0000006,Ingrid Bergman,tt0034583
nm0000006,Ingrid Bergman,tt0038109
nm0000006,Ingrid Bergman,tt0036855
nm0000006,Ingrid Bergman,tt0038787
nm0000007,Humphrey Bogart,tt0034583
nm0000007,Humphrey Bogart,tt0043265
nm0000007,Humphrey Bogart,tt0037382
nm0000007,Humphrey Bogart,tt0033870
nm0000008,Marlon Brando,tt0078788
nm0000008,Marlon Brando,tt0068646
nm0000008,Marlon Brando,tt0047296
nm0000008,Marlon Brando,tt0070849
nm0000009,Richard Burton,tt0061184
nm0000009,Richard Burton,tt0087803
nm0000009,Richard Burton,tt0059749
nm0000009,Richard Burton,tt0057877
nm0000010,James Cagney,tt0029870
nm0000010,James Cagney,tt0031867
nm0000010,James Cagney,tt0042041
nm0000010,James Cagney,tt0034236
nm0000011,Gary Cooper,tt0044706
nm0000011,Gary Cooper,tt0034167
nm0000011,Gary Cooper,tt0027996
nm0000011,Gary Cooper,tt0033373
nm0000012,Bette Davis,tt0042192
nm0000012,Bette Davis,tt0056687
nm0000012,Bette Davis,tt0031210
nm0000012,Bette Davis,tt0035140
nm0000013,Doris Day,tt0048317
nm0000013,Doris Day,tt0045591
nm0000013,Doris Day,tt0053172
nm0000013,Doris Day,tt0040745
nm0000014,Olivia de Havilland,tt0031381
nm0000014,Olivia de Havilland,tt0041452
nm0000014,Olivia de Havilland,tt0029843
nm0000014,Olivia de Havilland,tt0040806
nm0000015,James Dean,tt0048028
nm0000015,James Dean,tt0048545
nm0000015,James Dean,tt0049261
nm0000015,James Dean,tt0039123
nm0000016,Georges Delerue,tt0091763
nm0000016,Georges Delerue,tt0096320
nm0000016,Georges Delerue,tt0069946
nm0000016,Georges Delerue,tt0079477
nm0000017,Marlene Dietrich,tt0051201
nm0000017,Marlene Dietrich,tt0021156
nm0000017,Marlene Dietrich,tt0055031
nm0000017,Marlene Dietrich,tt0052311
nm0000018,Kirk Douglas,tt0043338
nm0000018,Kirk Douglas,tt0080736
nm0000018,Kirk Douglas,tt0054331
nm0000018,Kirk Douglas,tt0049456
nm0000019,Federico Fellini,tt0056801
nm0000019,Federico Fellini,tt0050783
nm0000019,Federico Fellini,tt0047528
nm0000019,Federico Fellini,tt0053779
nm0000020,Henry Fonda,tt0050083
nm0000020,Henry Fonda,tt0082846
nm0000020,Henry Fonda,tt0032551
nm0000020,Henry Fonda,tt0033804
nm0000021,Joan Fontaine,tt0032976
nm0000021,Joan Fontaine,tt0034248
nm0000021,Joan Fontaine,tt0036969
nm0000021,Joan Fontaine,tt0039504
nm0000022,Clark Gable,tt0025316
nm0000022,Clark Gable,tt0031381
nm0000022,Clark Gable,tt0023382
nm0000022,Clark Gable,tt0026752
nm0000023,Judy Garland,tt0032138
nm0000023,Judy Garland,tt0037059
nm0000023,Judy Garland,tt0047522
nm0000023,Judy Garland,tt0055031
nm0000024,John Gielgud,tt0082031
nm0000024,John Gielgud,tt0071877
nm0000024,John Gielgud,tt0045943
nm0000024,John Gielgud,tt0028231
nm0000025,Jerry Goldsmith,tt0119488
nm0000025,Jerry Goldsmith,tt0077269
nm0000025,Jerry Goldsmith,tt0117731
nm0000025,Jerry Goldsmith,tt0112715

In [0]:
%sql SELECT isAdult, COUNT(*)
FROM bronze.title_basics
--WHERE isAdult = 0 OR isAdult = 1
GROUP BY isAdult

isAdult,count(1)
1987,13
2016,20
2012,1
2020,9
1958,1
1972,29
1988,5
2019,7
2017,17
1977,20
2014,6
1971,3
1984,41
2013,8
1982,32
0,11180611
1965,1
1981,18
1978,130
1974,33
1959,1
2018,9
1964,1
1976,18
1968,24
1967,9
1966,25
2022,2
1973,18
1983,25
1969,19
2023,7
1980,66
1,373279
2021,1
1986,17
2024,4
1985,83
1979,63
2015,28
1975,18
1970,6
2011,1
2005,1
\N,1

In [0]:
%sql SELECT tconst, titleType, originalTitle, startYear as year,
CASE 
  WHEN isAdult = 1 THEN TRUE
  WHEN isAdult = 0 THEN FALSE
END AS isAdult
FROM bronze.title_basics
WHERE isAdult = 0 OR isAdult = 1

In [0]:
%sql CREATE TABLE silver.title_basics
AS SELECT tconst, titleType, originalTitle, startYear as year,
CASE 
  WHEN isAdult = 1 THEN TRUE
  WHEN isAdult = 0 THEN FALSE
END AS isAdult
FROM bronze.title_basics
WHERE isAdult = 0 OR isAdult = 1

In [0]:
%sql SELECT * FROM silver.title_basics
LIMIT 100

tconst,titleType,originalTitle,year,isAdult
tt0000001,short,Carmencita,1894,false
tt0000002,short,Le clown et ses chiens,1892,false
tt0000003,short,Pauvre Pierrot,1892,false
tt0000004,short,Un bon bock,1892,false
tt0000005,short,Blacksmith Scene,1893,false
tt0000006,short,Chinese Opium Den,1894,false
tt0000007,short,Corbett and Courtney Before the Kinetograph,1894,false
tt0000008,short,Edison Kinetoscopic Record of a Sneeze,1894,false
tt0000009,movie,Miss Jerry,1894,false
tt0000010,short,La sortie de l'usine Lumière à Lyon,1895,false
tt0000011,short,Akrobatisches Potpourri,1895,false
tt0000012,short,L'arrivée d'un train à La Ciotat,1896,false
tt0000013,short,Le débarquement du congrès de photographie à Lyon,1895,false
tt0000014,short,L'arroseur arrosé,1895,false
tt0000015,short,Autour d'une cabine,1894,false
tt0000016,short,Barque sortant du port,1895,false
tt0000017,short,Italienischer Bauerntanz,1895,false
tt0000018,short,Das boxende Känguruh,1895,false
tt0000019,short,The Clown Barber,1898,false
tt0000020,short,The Derby 1895,1895,false
tt0000022,short,Les forgerons,1895,false
tt0000023,short,Baignade en mer,1895,false
tt0000024,short,Opening of the Kiel Canal,1895,false
tt0000025,short,The Oxford and Cambridge University Boat Race,1896,false
tt0000026,short,Partie d'écarté,1896,false
tt0000027,short,Place des Cordeliers à Lyon,1895,false
tt0000028,short,La pêche aux poissons rouges,1895,false
tt0000029,short,Repas de bébé,1895,false
tt0000030,short,Rough Sea at Dover,1895,false
tt0000031,short,Le saut à la couverture,1895,false
tt0000032,short,Die Serpentintänzerin,1895,false
tt0000033,short,La voltige,1895,false
tt0000034,short,Arrivée d'un train gare de Vincennes,1896,false
tt0000035,short,L'arroseur,1896,false
tt0000036,short,Awakening of Rip,1896,false
tt0000037,short,Baignade en mer,1896,false
tt0000038,short,The Ball Game,1898,false
tt0000039,short,Barnet Horse Fair,1896,false
tt0000040,short,Barque sortant du port de Trouville,1896,false
tt0000041,short,Bataille de neige,1897,false
tt0000042,short,Bateau-mouche sur la Seine,1896,false
tt0000043,short,Batteuse à vapeur,1896,false
tt0000044,short,Le bivouac,1896,false
tt0000045,short,Les blanchisseuses,1896,false
tt0000046,short,Bois de Boulogne,1896,false
tt0000047,short,Boulevard des Italiens,1896,false
tt0000048,short,The Boxing Kangaroo,1896,false
tt0000049,short,"Boxing Match; or, Glove Contest",1896,false
tt0000050,short,Bébé et fillettes,1896,false
tt0000051,short,Campement de bohémiens,1896,false
tt0000052,short,Ruraux au galop,1896,false
tt0000053,short,A Chegada do Comboio Inaugural à Estação Central do Porto,1897,false
tt0000054,short,Les chevaux de bois,1896,false
tt0000055,short,Le chiffonnier,1896,false
tt0000056,short,Uma Corrida de Touros no Campo Pequeno,1896,false
tt0000057,short,Cortège de tzar allant à Versailles,1896,false
tt0000058,short,Cortège de tzar au Bois de Boulogne,1896,false
tt0000059,short,Couronnement de la rosière,1896,false
tt0000060,short,Dancing Darkies,1896,false
tt0000061,short,Dancing Girls,1896,false
tt0000062,short,Danse serpentine,1896,false
tt0000063,short,Dessinateur express,1896,false
tt0000064,short,Dessinateur: Chamberlain,1896,false
tt0000065,short,Dessinateur: Reine Victoria,1896,false
tt0000066,short,Dessinateur: Von Bismark,1896,false
tt0000067,short,Dix chapeaux en 60 secondes,1896,false
tt0000068,short,Déchargement de bateaux,1896,false
tt0000069,short,Défense d'afficher,1896,false
tt0000070,short,Démolition d'un mur,1896,false
tt0000071,short,Départ des automobiles,1896,false
tt0000072,short,Départ des officiers,1896,false
tt0000073,short,Effets de mer sur les rochers,1896,false
tt0000074,short,Enfants jouant sur la plage,1896,false
tt0000075,short,Escamotage d'une dame au théâtre Robert Houdin,1896,false
tt0000076,short,Exit of Rip and the Dwarf,1896,false
tt0000077,short,"Le fakir, mystère indien",1896,false
tt0000078,short,Feira de Gado na Corujeira,1896,false
tt0000079,short,La gare Saint-Lazare,1896,false
tt0000080,short,Grandes manoeuvres,1896,false
tt0000081,short,Les haleurs de bateaux,1896,false
tt0000082,short,A Hard Wash,1896,false
tt0000083,short,Les indiscrets,1896,false
tt0000084,short,Les ivrognes,1896,false
tt0000085,short,Jardinier brûlant des herbes,1896,false
tt0000086,short,Jetée et plage de Trouville (1er partie),1896,false
tt0000087,short,Jetée et plage de Trouville (2e partie),1896,false
tt0000088,short,Jour de marché à Trouville,1896,false
tt0000089,short,Départ de Jérusalem en chemin de fer,1897,false
tt0000090,short,Libération des territoriaux,1896,false
tt0000091,short,Le manoir du diable,1896,false
tt0000092,short,Marée montante sur Brise-Larmes,1896,false
tt0000093,short,Melbourne,1896,false
tt0000094,short,Miss de Vere,1896,false
tt0000095,short,Le papier protée,1896,false
tt0000096,short,Place Saint-Augustin,1896,false
tt0000097,short,"Place de l'Opéra, 1er aspect",1896,false
tt0000098,short,"Place de l'Opéra, 2e aspect",1896,false
tt0000099,short,Place de la Bastille,1896,false
tt0000100,short,Place de la Concorde,1896,false
tt0000101,short,Place du théâtre français,1896,false

In [0]:
%sql DROP DATABASE IF EXISTS gold CASCADE

In [0]:
%sql CREATE DATABASE gold

In [0]:
%sql SELECT * 
FROM silver.title_basics AS T,
  silver.name_basics_titles AS N
WHERE N.tconst = T.tconst
LIMIT 10

tconst,titleType,originalTitle,year,isAdult,nconst,primaryName,tconst
tt0000015,short,Autour d'une cabine,1894,false,nm1335271,Gaston Paulin,tt0000015
tt0000174,short,Výstavní párkar a lepic plakátù,1898,false,nm0471818,Jan Krízenecký,tt0000174
tt0000174,short,Výstavní párkar a lepic plakátù,1898,false,nm1024447,Ferdinand Gýra,tt0000174
tt0000305,short,L'Habanera,1900,false,nm0112631,Valentine Brouat,tt0000305
tt0000451,short,Mary Jane's Mishap,1903,false,nm0809419,Laura Bayley,tt0000451
tt0000621,short,That Fatal Sneeze,1907,false,nm0693275,Gertie Potter,tt0000621
tt0000621,short,That Fatal Sneeze,1907,false,nm2140812,Thurston Harris,tt0000621
tt0000748,short,The Redman and the Child,1908,false,nm0537238,Johnny Mahr,tt0000748
tt0000748,short,The Redman and the Child,1908,false,nm0409390,Charles Inslee,tt0000748
tt0000862,movie,Faldgruben,1909,false,nm0878467,Emanuel Tvede,tt0000862

In [0]:
%sql CREATE TABLE gold.names_titles AS
SELECT N.nconst, N.primaryName, T.*
FROM silver.title_basics AS T,
  silver.name_basics_titles AS N
WHERE N.tconst = T.tconst

In [0]:
%sql SELECT * FROM gold.names_titles
ORDER BY originalTitle, primaryName
LIMIT 1000

nconst,primaryName,tconst,titleType,originalTitle,year,isAdult
nm2506382,Stephen Sung,tt2386381,tvSeries,!Next?,1994,false
nm5794862,Aaron Margolis-Greenbaum,tt21091602,tvSeries,#,2022,false
nm11054261,Aaron Maurice,tt21091602,tvSeries,#,2022,false
nm12571512,Adrienne Schmucker,tt21091602,tvSeries,#,2022,false
nm15269991,Aftin Brown,tt21091602,tvSeries,#,2022,false
nm14012320,Alyson Cline,tt21091602,tvSeries,#,2022,false
nm12646409,Alyssa Baskins,tt21091602,tvSeries,#,2022,false
nm11091998,Amelia Morris,tt21091602,tvSeries,#,2022,false
nm13827163,Amity Aschliman,tt21091602,tvSeries,#,2022,false
nm15262189,Anastasia Hinton,tt21091602,tvSeries,#,2022,false
nm15437466,Andrea White,tt21091602,tvSeries,#,2022,false
nm13825823,Ariana Modi,tt21091602,tvSeries,#,2022,false
nm4299902,Arthur Guttilla,tt6748908,short,#,2012,false
nm13777667,Askia Shareef,tt21091602,tvSeries,#,2022,false
nm13933934,Austin Uebelhor,tt21091602,tvSeries,#,2022,false
nm14113779,Baiba Revizore,tt21091602,tvSeries,#,2022,false
nm14012319,Bette Combs,tt21091602,tvSeries,#,2022,false
nm15393425,Brad Armstrong,tt21091602,tvSeries,#,2022,false
nm13966886,Brad Rigler,tt21091602,tvSeries,#,2022,false
nm5675097,Brian Ludlow,tt2399574,short,#,2012,false
nm15805392,Bruno Libonati,tt28240550,movie,#,2022,false
nm11091994,Bryan Carter,tt21091602,tvSeries,#,2022,false
nm15393428,Bryce Lee Schumacher,tt21091602,tvSeries,#,2022,false
nm5222261,Cacá Ottoni,tt28240550,movie,#,2022,false
nm3268959,Caio Sóh,tt28240550,movie,#,2022,false
nm15249768,Casey Clouser,tt21091602,tvSeries,#,2022,false
nm11091985,Cassia Margolis,tt21091602,tvSeries,#,2022,false
nm15393431,Chelsea Snedden,tt21091602,tvSeries,#,2022,false
nm15269989,Chris Cline,tt21091602,tvSeries,#,2022,false
nm5794861,Cindie Harp,tt21091602,tvSeries,#,2022,false
nm11091976,Corey Randm Ellis,tt21091602,tvSeries,#,2022,false
nm2939731,Dane Rogers,tt21091602,tvSeries,#,2022,false
nm15393419,Danielle Lewis,tt21091602,tvSeries,#,2022,false
nm15042814,Darron Finesilver,tt21091602,tvSeries,#,2022,false
nm13933935,Dave Carr,tt21091602,tvSeries,#,2022,false
nm6529195,David Schneider,tt3762918,short,#,2014,false
nm13827164,DeShawn L Wilson Sr.,tt21091602,tvSeries,#,2022,false
nm14096233,Del Vaulx,tt21091602,tvSeries,#,2022,false
nm13855261,Derrick Belmar,tt21091602,tvSeries,#,2022,false
nm5794853,Desi Rybolt,tt21091602,tvSeries,#,2022,false
nm15393432,Donnie Lines,tt21091602,tvSeries,#,2022,false
nm2732166,Doug Szczesny,tt3762918,short,#,2014,false
nm15256857,Dustin Druley,tt21091602,tvSeries,#,2022,false
nm5276409,Dylan Fitzpatrick,tt2399574,short,#,2012,false
nm14032963,DéJon LéTray,tt21091602,tvSeries,#,2022,false
nm11227464,Eduardo Reyes,tt28240550,movie,#,2022,false
nm15262994,Emmanuel T.,tt21091602,tvSeries,#,2022,false
nm13827165,Falesia Tiller,tt21091602,tvSeries,#,2022,false
nm4712135,Farkas André,tt6748908,short,#,2012,false
nm15393435,Frankie Grizz,tt21091602,tvSeries,#,2022,false
nm16675176,Gabriel Antunes,tt28240550,movie,#,2022,false
nm15241404,Hanna Causby,tt21091602,tvSeries,#,2022,false
nm11091984,Harriet Ross,tt21091602,tvSeries,#,2022,false
nm15383136,Heather Smith Kenjorski,tt21091602,tvSeries,#,2022,false
nm15393423,Heather Walker,tt21091602,tvSeries,#,2022,false
nm13933793,Ishon McIver,tt21091602,tvSeries,#,2022,false
nm13831589,J.F. Alexander McQueary,tt21091602,tvSeries,#,2022,false
nm10420317,Jacob Pettyjohn,tt21091602,tvSeries,#,2022,false
nm6529522,Jaime Szczesny,tt3762918,short,#,2014,false
nm5277322,Jake Comer,tt2399574,short,#,2012,false
nm10252650,Jalen Anderson,tt21091602,tvSeries,#,2022,false
nm10506558,Jalen Anderson,tt21091602,tvSeries,#,2022,false
nm10469732,Jalil Stephens,tt21091602,tvSeries,#,2022,false
nm5838191,James Kenjorski,tt21091602,tvSeries,#,2022,false
nm15241403,Jaquan Scott,tt21091602,tvSeries,#,2022,false
nm13816725,Jasmine Rashá,tt21091602,tvSeries,#,2022,false
nm15262995,Jayme Peyton,tt21091602,tvSeries,#,2022,false
nm13816723,Jeff Angel,tt21091602,tvSeries,#,2022,false
nm15393430,Jeffery Rhodes,tt21091602,tvSeries,#,2022,false
nm15393422,Jennifer Glunt,tt21091602,tvSeries,#,2022,false
nm8436133,Jessica Applegate,tt21091602,tvSeries,#,2022,false
nm14032964,Jetta Vaughn,tt21091602,tvSeries,#,2022,false
nm13825824,John Brennan Hayes,tt21091602,tvSeries,#,2022,false
nm13950265,Jon Lindley,tt21091602,tvSeries,#,2022,false
nm15393433,Jose Munoz,tt21091602,tvSeries,#,2022,false
nm10931459,João Vancini,tt28240550,movie,#,2022,false
nm13855260,Justin Ralston,tt21091602,tvSeries,#,2022,false
nm11282477,Kaitlynn Nailon,tt21091602,tvSeries,#,2022,false
nm13816722,Kaleb Isabell,tt21091602,tvSeries,#,2022,false
nm15383147,Kaleb Sweatt,tt21091602,tvSeries,#,2022,false
nm15301730,Karen Webster-Cones,tt21091602,tvSeries,#,2022,false
nm13816724,Keiston Drake,tt21091602,tvSeries,#,2022,false
nm13827167,Kendra Akinsuroju,tt21091602,tvSeries,#,2022,false
nm5541110,Kerra Wagener,tt21091602,tvSeries,#,2022,false
nm13863046,Kiley Mahaffey,tt21091602,tvSeries,#,2022,false
nm11771782,Kurt Watkins,tt21091602,tvSeries,#,2022,false
nm15393429,Kyle Buck,tt21091602,tvSeries,#,2022,false
nm12092848,Lauren Nowlin,tt21091602,tvSeries,#,2022,false
nm13863048,Lauren Nowlin,tt21091602,tvSeries,#,2022,false
nm15393434,Lauren Warfield,tt21091602,tvSeries,#,2022,false
nm11091989,Lawrence Mark,tt21091602,tvSeries,#,2022,false
nm15393420,Leah Heath,tt21091602,tvSeries,#,2022,false
nm12681140,Leona Jones,tt21091602,tvSeries,#,2022,false
nm13933791,Leroy Delph,tt21091602,tvSeries,#,2022,false
nm13863047,Liz Porter,tt21091602,tvSeries,#,2022,false
nm15482541,Matthew Walls,tt21091602,tvSeries,#,2022,false
nm13827168,Melissa Hamilton,tt21091602,tvSeries,#,2022,false
nm13855262,Michael Dabney,tt21091602,tvSeries,#,2022,false
nm5426290,Mike Longo,tt2399574,short,#,2012,false
nm15393421,Mike Menke,tt21091602,tvSeries,#,2022,false
nm5794855,Molly Dykstra,tt21091602,tvSeries,#,2022,false
nm13102484,Morgan Rae Webster,tt21091602,tvSeries,#,2022,false
nm5794854,Natalie George,tt21091602,tvSeries,#,2022,false
nm15393424,Nathalie Armstrong,tt21091602,tvSeries,#,2022,false
nm13827169,Nicole Risley,tt21091602,tvSeries,#,2022,false
nm14096232,Peter Heinz,tt21091602,tvSeries,#,2022,false
nm10418024,Preston Dildine,tt21091602,tvSeries,#,2022,false
nm13070986,Rhay Polster,tt28240550,movie,#,2022,false
nm15269990,Rich Barker,tt21091602,tvSeries,#,2022,false
nm15249674,Rick Northam,tt21091602,tvSeries,#,2022,false
nm13827170,Ricky Cortez,tt21091602,tvSeries,#,2022,false
nm11091973,Roci Contreras,tt21091602,tvSeries,#,2022,false
nm3907642,Rudá Capriles,tt28240550,movie,#,2022,false
nm12608574,Ryan May,tt21091602,tvSeries,#,2022,false
nm6529493,Sara Jaouen,tt3762918,short,#,2014,false
nm13777644,Sarah Kinsey,tt21091602,tvSeries,#,2022,false
nm5794856,Sarah Margolis-Greenbaum,tt21091602,tvSeries,#,2022,false
nm15383148,Seantell Conley,tt21091602,tvSeries,#,2022,false
nm14113780,Selene Loomis,tt21091602,tvSeries,#,2022,false
nm11795684,Seth Procasky,tt21091602,tvSeries,#,2022,false
nm10313401,Shannon Samson,tt21091602,tvSeries,#,2022,false
nm15393436,Shawn Hayes,tt21091602,tvSeries,#,2022,false
nm15333552,Sibyly Mia,tt21091602,tvSeries,#,2022,false
nm15393427,Siegfried Cheshire,tt21091602,tvSeries,#,2022,false
nm13827171,Sonya Capers,tt21091602,tvSeries,#,2022,false
nm13827172,Spencer Elliott,tt21091602,tvSeries,#,2022,false
nm13933792,Stephen Hollenbeck,tt21091602,tvSeries,#,2022,false
nm13827173,Tamilya Miller,tt21091602,tvSeries,#,2022,false
nm13827174,Tania Wineglass,tt21091602,tvSeries,#,2022,false
nm13827175,Tasha Ellis,tt21091602,tvSeries,#,2022,false
nm13777668,Tennah McDonald,tt21091602,tvSeries,#,2022,false
nm15393426,Terry Shepard,tt21091602,tvSeries,#,2022,false
nm15263001,Thomas Davenport,tt21091602,tvSeries,#,2022,false
nm15269992,Thomas Davenport,tt21091602,tvSeries,#,2022,false
nm12246983,Toney Crawford,tt21091602,tvSeries,#,2022,false
nm13777645,Tyson Cox,tt21091602,tvSeries,#,2022,false
nm4273738,Yasmin Garcez,tt28240550,movie,#,2022,false
nm11091980,Zachary Antle,tt21091602,tvSeries,#,2022,false
nm2543090,Zak Longo,tt2399574,short,#,2012,false
nm4959166,Hannes Bruun,tt28317921,short,# #,2009,false
nm15023375,Kamil Goerlich,tt28317921,short,# #,2009,false
nm15023376,Linda Sepp,tt28317921,short,# #,2009,false
nm15023374,Magalie Armand,tt28317921,short,# #,2009,false
nm15023373,Roderick Warich,tt28317921,short,# #,2009,false
nm15023378,Roland Stuprich,tt28317921,short,# #,2009,false
nm14820790,Briana Symone',tt29899777,movie,# 1 Fan,2024,false
nm14155566,Kody Bean,tt29899777,movie,# 1 Fan,2024,false
nm13985675,Christian Meinberger,tt21917854,tvSpecial,# Deine Wahl,2017,false
nm9598348,Ischtar Isik,tt21917854,tvSpecial,# Deine Wahl,2017,false
nm12616528,Lisa Ruhfus,tt21917854,tvSpecial,# Deine Wahl,2017,false
nm6048937,Magnus Wacinski,tt21917854,tvSpecial,# Deine Wahl,2017,false
nm9478613,Manuel Schmitt,tt21917854,tvSpecial,# Deine Wahl,2017,false
nm13985674,Schmidt Martin,tt21917854,tvSpecial,# Deine Wahl,2017,false
nm10701202,Leila Hazuki,tt10348576,video,# En [Interchange],2019,true
nm16917318,Barbara Hines,tt35417622,short,# No Regrets,2021,false
nm16917317,Dan Anderson,tt35417622,short,# No Regrets,2021,false
nm16917319,Julia Hebner,tt35417622,short,# No Regrets,2021,false
nm12646015,Paxton Smith,tt35417622,short,# No Regrets,2021,false
nm14171700,Anna Burdette,tt21820794,short,#$%!&@!,2023,false
nm14716673,Dustin Loucks,tt21820794,short,#$%!&@!,2023,false
nm14837092,Miles Tuttle,tt21820794,short,#$%!&@!,2023,false
nm13952008,Nick Bucci,tt21820794,short,#$%!&@!,2023,false
nm13299678,Stephen Sarrasin,tt21820794,short,#$%!&@!,2023,false
nm13783262,Rielle Oase,tt29606256,video,#05003F,\N,false
nm10482981,Carlos Stephens,tt13396124,tvSeries,#08527,2021,false
nm9425813,Fred Fields,tt13396124,tvSeries,#08527,2021,false
nm4671179,Ali Strauch,tt2057889,short,#1,2010,false
nm4436161,Carl Schutt,tt2057889,short,#1,2010,false
nm3967007,Cynthia Ellen Newman,tt2057889,short,#1,2010,false
nm2039994,Daniel Gahr,tt0480502,short,#1,2005,false
nm4435392,Daniel Gast,tt2057889,short,#1,2010,false
nm10568661,Daniel Smith,tt13409842,short,#1,2020,false
nm3934934,Daniel Waldrop,tt2057889,short,#1,2010,false
nm3933148,David Fox,tt2057889,short,#1,2010,false
nm4436082,Devin Peluso,tt2057889,short,#1,2010,false
nm4671415,Forrest Stevens,tt2057889,short,#1,2010,false
nm4671793,Grace Barerro,tt2057889,short,#1,2010,false
nm3962065,Jason Pollard,tt1611790,video,#1,2010,false
nm9008157,John Morgan,tt6915008,movie,#1,\N,false
nm4671699,Joseph Sbrilli,tt2057889,short,#1,2010,false
nm4671764,Josh Lewis,tt2057889,short,#1,2010,false
nm4671162,Juan Breedlove,tt2057889,short,#1,2010,false
nm1631138,Jud Heathcote,tt6915008,movie,#1,\N,false
nm9008156,Katie Francis,tt6915008,movie,#1,\N,false
nm4671700,Katie Shupe,tt2057889,short,#1,2010,false
nm6039495,Kelsey Ramsden,tt6915008,movie,#1,\N,false
nm6620423,Marion Castéra,tt3852602,short,#1,2009,false
nm4671240,Megan Seeds,tt2057889,short,#1,2010,false
nm4671713,Mike Devine,tt2057889,short,#1,2010,false
nm1933842,Nicholas J. Giordano,tt0480502,short,#1,2005,false
nm6620422,Noamir Castéra,tt3852602,short,#1,2009,false
nm6620424,Romain Castéra,tt3852602,short,#1,2009,false
nm1866067,Scotty Bowman,tt6915008,movie,#1,\N,false
nm3933872,Steven Michael King,tt2057889,short,#1,2010,false
nm2062903,Thomas McMillan,tt0480502,short,#1,2005,false
nm4257360,Vijay Nazareth,tt1813109,video,#1,2010,false
nm16148990,Aaron Montreal,tt34748756,short,#1 Bad Dad,2025,false
nm16767129,Eli Denson,tt34748756,short,#1 Bad Dad,2025,false
nm13547361,Kyle Selby,tt34748756,short,#1 Bad Dad,2025,false
nm14508494,Liliana Bonilla,tt34748756,short,#1 Bad Dad,2025,false
nm11382384,Shakera J. Robinson,tt34748756,short,#1 Bad Dad,2025,false
nm6358836,Anders Link,tt3597346,short,#1 Beauty Nail Salon,2014,false
nm6358837,Paul Tran,tt3597346,short,#1 Beauty Nail Salon,2014,false
nm2423035,Adam Wright,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004567,Allana St. John,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004636,Annie Dorgan,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004475,Bianca Swarta,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004471,Bre Reinsen,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004431,Caroline Lampkin,tt1637976,video,#1 Cheerleader Camp,2010,false
nm0219752,Cheryl Dent,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004389,Elyse Falzone,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3493417,Emi Eliza,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004444,Garrett Mullen,tt1637976,video,#1 Cheerleader Camp,2010,false
nm1548215,Harmony Blossom,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3871298,Heather Nemeth,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004323,Jamie Drew,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4248119,Janelle Lynette Cruz,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004576,Jeff Duchesner,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004516,Jenelle Lancaster,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004650,Joe Richey,tt1637976,video,#1 Cheerleader Camp,2010,false
nm0676856,John Richard Petersen,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3185938,Jordan Davis,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004490,Joseph Fanglli,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4023252,Jullien Avondo,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3890423,Justine Zimbron,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004510,Kaitlyn Shipley,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004382,Karlina Mahle,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004566,Kelli Hammond,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4859180,Lexi Newman,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004562,Liberty Freeman,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004540,Lindsey Mayer,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3157009,Makenzi Swicegood,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004613,Mandi Mettler,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004603,Matana Erin,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004583,Matthew Litwyner,tt1637976,video,#1 Cheerleader Camp,2010,false
nm9058603,Natasha Morgan,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004506,Paul Romero Jr.,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004330,Richard Jordan,tt1637976,video,#1 Cheerleader Camp,2010,false
nm10235856,Robert Peters,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004573,Roger Chagnon,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3643609,Sally Powers,tt1637976,video,#1 Cheerleader Camp,2010,false
nm5424960,Saman Nasir,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004542,Sara Anne Fahey,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3215890,Seth Cassell,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004637,Sierra Paige,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004355,Starkesha Brown Robinson,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004551,Sundral Nicole Sizemore,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004489,Tyler Cantrell,tt1637976,video,#1 Cheerleader Camp,2010,false
nm0376626,Vanessa Henderson,tt1637976,video,#1 Cheerleader Camp,2010,false
nm3731366,Vanessa Huntoon,tt1637976,video,#1 Cheerleader Camp,2010,false
nm4004552,William Mann,tt1637976,video,#1 Cheerleader Camp,2010,false
nm12929572,Alexander Prynkiewicz,tt15410938,tvSeries,#1 Chicken,2021,false
nm12018371,Anthony Jabro,tt15410938,tvSeries,#1 Chicken,2021,false
nm8818930,Caleb Marshall,tt15410938,tvSeries,#1 Chicken,2021,false
nm12364313,Deestroying,tt15410938,tvSeries,#1 Chicken,2021,false
nm4816478,Jessica Ho,tt15410938,tvSeries,#1 Chicken,2021,false
nm10270020,Madison Laughlin,tt15410938,tvSeries,#1 Chicken,2021,false
nm12929573,Noah Rojas,tt15410938,tvSeries,#1 Chicken,2021,false
nm12929575,Quenlin Blackwell,tt15410938,tvSeries,#1 Chicken,2021,false
nm12929574,Tasha Proctor,tt15410938,tvSeries,#1 Chicken,2021,false
nm9558773,Alexander Joshua Sta. Maria,tt7879814,short,#1 Dad,2017,false
nm11868735,Amanda Köhler,tt14907272,short,#1 Dad,2021,false
nm12376570,Chido Sounds,tt14907272,short,#1 Dad,2021,false
nm5448353,Conor Biddle,tt6170852,short,#1 Dad,2016,false
nm12690249,Halle Fletcher,tt14907272,short,#1 Dad,2021,false
nm1144569,Jeff Jackson,tt14907272,short,#1 Dad,2021,false
nm8527256,Jennifer Obasohan,tt6170852,short,#1 Dad,2016,false
nm8527257,Jesse Pamintuan,tt6170852,short,#1 Dad,2016,false
nm11866755,John M. Hoffman,tt14907272,short,#1 Dad,2021,false
nm9558776,Kevin Gallegos,tt7879814,short,#1 Dad,2017,false
nm9558774,Mason Banks,tt7879814,short,#1 Dad,2017,false
nm6681482,Nate Edmiston,tt14907272,short,#1 Dad,2021,false
nm8527254,Nile Hawver,tt6170852,short,#1 Dad,2016,false
nm11868006,Taylor Sandstrom,tt14907272,short,#1 Dad,2021,false
nm11866753,Tristan Johnson,tt14907272,short,#1 Dad,2021,false
nm11898818,Livia Rae,tt14533840,short,#1 Fan,2021,false
nm1733077,Alejandro D. Otero,tt0436005,video,#1 Fan: A Darkomentary,2005,false
nm14306421,Amanda Lodge,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm15858111,Canaan Richardson,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm3835964,Dave Newberg,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm15997621,Fatima Maymoon,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm7977287,J.N. Wiedle,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm12336261,Jocelyn Montoya,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm8793503,Michelle Santoso,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm14139855,Mirren Hollison,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm7635340,Mona Chalabi,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm7083306,Paige Halsey Warren,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm3731362,Paul Elia,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm11546840,Randa Jarrar,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm15976837,Reem Youssef,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm6639621,Robert Gilliam,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm7877594,Ruby Eva,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm6009913,Sabrina Mahfouz,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm16322838,Serena Abdallah,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm13011408,YueTong Tsen,tt18566094,tvSeries,#1 Happy Family USA,2025,false
nm3739416,Iris Mirnezami,tt8363132,video,#1 Lab'dance,2018,false
nm4669962,Kevin Alan Kent,tt4089286,movie,#1 Mamarazzi,\N,false
nm6819638,Marco Rea,tt4089286,movie,#1 Mamarazzi,\N,false
nm4410394,Al Pierre,tt2346170,movie,#1 Serial Killer,2013,false
nm5232016,Arzoo Nasarabadi,tt2346170,movie,#1 Serial Killer,2013,false
nm5221457,Christie Gaynor,tt2346170,movie,#1 Serial Killer,2013,false
nm5613368,Dean Sloan,tt2346170,movie,#1 Serial Killer,2013,false
nm5232411,Evan Kodani,tt2346170,movie,#1 Serial Killer,2013,false
nm5223232,James Schaff,tt2346170,movie,#1 Serial Killer,2013,false
nm2661331,Jesse Wang,tt2346170,movie,#1 Serial Killer,2013,false
nm5222647,Jinxia Ma,tt2346170,movie,#1 Serial Killer,2013,false
nm4899108,Jocelyn Wang,tt2346170,movie,#1 Serial Killer,2013,false
nm5232353,Karen M. Gee,tt2346170,movie,#1 Serial Killer,2013,false
nm4747188,Kasie Callaway,tt2346170,movie,#1 Serial Killer,2013,false
nm5062115,Kristopher Baumgartner,tt2346170,movie,#1 Serial Killer,2013,false
nm4753356,Marlene Kuo-Morinaga,tt2346170,movie,#1 Serial Killer,2013,false
nm4361152,Matthias Chrans,tt2346170,movie,#1 Serial Killer,2013,false
nm1128056,Michael Alton,tt2346170,movie,#1 Serial Killer,2013,false
nm5232076,Minna Kim,tt2346170,movie,#1 Serial Killer,2013,false
nm5232004,Mj Kang,tt2346170,movie,#1 Serial Killer,2013,false
nm3109366,Nicole Ding,tt2346170,movie,#1 Serial Killer,2013,false
nm5232122,Olivia Yu,tt2346170,movie,#1 Serial Killer,2013,false
nm5221898,Peter Shimamoto,tt2346170,movie,#1 Serial Killer,2013,false
nm5222648,Remi,tt2346170,movie,#1 Serial Killer,2013,false

In [0]:
%sql SELECT * FROM gold.names_titles
WHERE primaryName like "%Kevin Bacon%"
LIMIT 1000

nconst,primaryName,tconst,titleType,originalTitle,year,isAdult
nm8407192,Kevin Bacon Hervieux,tt6026054,tvMovie,Innu Nikamu: La Grande Tradition,2017,false
nm8407192,Kevin Bacon Hervieux,tt9207434,movie,Innu Nikamu: chanter la résistance,2017,false
nm0000102,Kevin Bacon,tt0164052,movie,Hollow Man,2000,false
nm0000102,Kevin Bacon,tt0327056,movie,Mystic River,2003,false
nm4025714,Kevin Bacon,tt8429394,movie,The Return,2020,false
nm4025714,Kevin Bacon,tt0098193,movie,The Return of Swamp Thing,1989,false
nm4025714,Kevin Bacon,tt1737781,video,The Suit,2010,false
nm3636162,Kevin Bacon,tt2063666,movie,Hello I Must Be Going,2012,false
nm4025714,Kevin Bacon,tt3067274,movie,The Editor,2014,false
nm9323132,Kevin Bacon,tt0259795,tvSeries,The Old Grey Whistle Test,1971,false
nm0000102,Kevin Bacon,tt0087277,movie,Footloose,1984,false
nm9323132,Kevin Bacon,tt5112578,movie,Super Dark Times,2017,false
nm3636162,Kevin Bacon,tt1954811,movie,See Girl Run,2012,false
nm9323132,Kevin Bacon,tt7470112,movie,The Comsat Angels Live 12-12-1981,1981,false
nm3636162,Kevin Bacon,tt4875654,movie,Sunset Park,2017,false
nm3636162,Kevin Bacon,tt2186712,movie,Long Nights Short Mornings,2016,false
nm10210267,Kevin Bacon,tt1554356,tvSeries,On the Case with Paula Zahn,2009,false
nm9323132,Kevin Bacon,tt33245920,short,The Comsat Angels Live @ Markthalle Hamburg,1984,false
nm0000102,Kevin Bacon,tt0361127,movie,The Woodsman,2004,false

In [0]:
%sql SELECT B.primaryName, COUNT(B.originalTitle) AS Quant_filmes
FROM gold.names_titles AS B
GROUP BY B.primaryName
ORDER BY Quant_filmes DESC

primaryName,Quant_filmes
David Smith,596
Michael Smith,555
Chris Smith,513
Mike Smith,504
Alex,499
Michael Johnson,498
David Williams,491
Chris Jones,484
Chris Johnson,482
David Brown,476
John Williams,469
David Jones,467
James Smith,467
John Smith,462
Steve Smith,445
Michael Williams,431
Andrew Smith,419
Mark Smith,418
David Lee,415
David,413
David Johnson,413
Brian Smith,407
Michael Brown,405
Ryan Smith,400
Chris,399
Michael,396
Mark Williams,395
Matt Smith,395
John,394
John Taylor,390
Mike,385
Chris Brown,380
Robert Smith,380
Paul Smith,379
Adam Smith,363
Ben Smith,363
David Miller,356
Mike Jones,353
Tim Smith,351
Mark Johnson,346
Chris Wilson,344
Michael Miller,341
Chris Miller,340
Daniel,340
Anna,338
Paul Williams,334
Eric Johnson,333
James Brown,333
Chris Williams,332
Jason Smith,327
Michael Jones,323
David White,323
John Murphy,322
John Kelly,321
Kevin Smith,321
Chris Martin,317
Jeff Smith,316
John Wilson,315
James,314
Justin Smith,314
Michael Davis,313
Brian Johnson,312
Maria,312
Sam Jones,310
Michael Thomas,309
Richard Smith,309
Sarah,308
John Anderson,308
David Taylor,303
Scott Smith,302
Sam,301
Steve Jones,301
Peter Smith,301
Chris Anderson,300
David Wilson,300
Paul Taylor,299
Alex Smith,299
James Williams,299
John Lee,298
Chris Taylor,296
Angel,296
John Miller,295
David Martin,294
John Davis,294
Mike Brown,293
Daniel Smith,293
Gurpreet Singh,292
Mike Johnson,291
Michelle,290
Max,289
Mark Jones,289
Eric Smith,288
Tony,288
Greg Smith,286
John Martin,286
John Harris,285
Michael Wilson,285
Aaron Smith,284
Paul Jones,284
Matt Jones,283
Rahul,283
Matthew Smith,282
Chris Davis,281
Chris Thompson,280
Paul,279
David Allen,279
John Brown,278
Lisa,277
David Harris,276
Chris White,276
Ben Johnson,276
Jason Brown,276
Thomas,275
Steve Brown,275
Robert Brown,274
Rajesh,274
Mike Williams,273
Ian Smith,272
James Wilson,272
Jessica,271
Richard Jones,271
David Scott,268
Dan Smith,268
Scott Johnson,267
Michael Lee,266
Suresh,265
John Moore,265
Kevin Johnson,265
Charlie,264
David Moore,264
Michael Scott,263
Nicole,263
Craig Smith,262
Scott Miller,262
Michael Anderson,262
Mark,261
Mark Wilson,261
Sabrina,260
Carlos Rodriguez,260
Dave Smith,260
Matt Brown,259
David Lewis,258
David Thomas,258
Robert Johnson,257
James Lee,257
Michael White,255
Michael Taylor,253
Mark Anderson,253
Mike Miller,252
Matt Taylor,252
John Johnson,252
Mike Davis,251
Christopher Smith,251
Peter,250
Michael Murphy,250
Sarah Smith,250
Kevin Williams,250
Sean Smith,248
John Campbell,248
Mark Harris,247
Mark Davis,247
Brian Jones,247
Paul Johnson,246
Nick Smith,245
David Hughes,245
Michael Moore,244
Mark Miller,244
Chris Kelly,244
Kevin Lee,244
Paul Martin,244
Tom,244
Chris Lee,243
Matt Johnson,243
Sean Kelly,242
Jason Miller,242
Joe,242
Kim,241
Amit Kumar,240
David Anderson,239
James Johnson,239
John Scott,239
Michael Thompson,238
Mark Taylor,238
Sandra,238
Kevin Jones,238
Jennifer,238
Chris Moore,238
Wei Wang,237
Ravi,237
Raju,237
Michael Lewis,237
James Taylor,237
John Thomas,236
Alex Jones,236
Steve,236
Ramesh,235
Jeff Johnson,235
Patrick Smith,235
David Hill,234
Ryan Williams,234
John King,234
Matt Williams,234
Andrew Brown,234
Chris Thomas,234
John Baker,233
Sam Smith,232
Linda,232
David King,232
James Davis,232
Robert Williams,231
Michael Kelly,231
Peter Jones,231
Jack,231
Vanessa,231
David Young,231
Kevin,231
Chris Young,230
Deepak,230
Andrew Miller,229
Tim Johnson,228
Nick,227
Peter Brown,227
James Moore,227
Josh Smith,226
John Thompson,226
Matt,225
Michael Martin,225
Steve Miller,224
Andrea,224
Chris Harris,224
David Thompson,222
David James,222
David Ross,222
Tom Smith,222
Jason,222
Laura,221
Jason Williams,221
John Morgan,220
James Jones,220
Brandon Smith,220
Eva,220
Krishna,219
Tina,219
James Anderson,219
David Rodriguez,219
Richard Johnson,219
John Adams,218
Chris Clark,218
Jenny,217
Andrew Wilson,217
John Clark,216
James Harris,216
Mark Thomas,216
Monica,215
Richard Williams,215
Tony Smith,214
Robert Jones,214
Ajay Kumar,214
David Green,213
Jason Lee,213
James Clark,213
Andrew Johnson,213
Daniel Garcia,213
Kevin Brown,212
Chris Allen,212
David Evans,212
Chris Hall,211
Sara,211
Mike Anderson,211
Vijay,211
John Roberts,211
Gary Smith,211
Manpreet Singh,211
Andrew Jones,211
Brad Smith,210
James Martin,210
Ben Jones,210
John Jackson,210
Chris Hill,209
Eric Brown,209
Alex Brown,209
Matt Miller,209
Sandeep Singh,209
Mark Brown,209
Alex Williams,209
Eric Anderson,209
Daniel Rodriguez,208
James Young,208
Richard Taylor,208
John Collins,207
Anil Kumar,207
Steve Johnson,206
Michael Green,206
John Wright,206
Brian Lee,205
Nina,205
Ryan Johnson,205
John Lewis,205
Mike Kelly,205
John White,205
Jack Smith,205
Michael Robinson,205
Kelly,204
Michael Harris,204
Vijay Kumar,204
Daniel Johnson,203
Brian Williams,203
Ryan Miller,203
Sunil Kumar,203
Jay,202
Paul Thompson,202
James Thompson,202
Ben Taylor,202
Paul Wilson,202
David Jackson,202
David Alexander,202
David Garcia,202
Robert Taylor,202
Lucy,202
John Hall,201
Richard Evans,201
Sean Murphy,201
Ryan,201
Dave,201
Jonathan Williams,200
Brian Murphy,200
Kiran,200
Dave Brown,200
Chris King,199
Chris Walker,199
James Miller,199
John Young,199
Ryan Jones,198
Michael Collins,198
Robert Lee,198
David Wright,198
Chris Lewis,198
Paul Brown,197
James Lewis,197
Julia,197
Joshua Smith,197
Tom Williams,197
James Allen,197
Manoj Kumar,197
Mike Wilson,197
Tim Jones,197
Eric Williams,197
Rob Smith,197
John Jones,196
Josh,196
Tony Brown,196
David Robinson,195
Jose Martinez,195
Stephen Smith,195
Marco,195
Christopher Jones,195
Mahesh,194
Richard Brown,194
Peter Williams,194
John O'Brien,194
Chris Collins,194
Natasha,194
Matthew Johnson,194
Michael Hall,193
John Stewart,193
Ravi Kumar,193
Victoria,193
Scott Anderson,193
Dan Johnson,193
David Mitchell,192
Andrew Williams,192
Matthew Brown,192
John Gray,192
Ben Wilson,192
Chris Robinson,191
Robert Miller,191
Robert,191
Bill Johnson,190
Robert Anderson,190
Arun Kumar,190
Brandon Jones,189
Adam,189
Andrew Lee,188
Carlos Garcia,188
Michael Ryan,188
Scott Taylor,188
Derek Smith,188
James Hall,188
Sasha,187
Richard,187
Daniel Brown,187
Michael Sullivan,187
Jonathan Smith,187
Mary,187
Lola,187
John Ross,186
Scott Brown,186
Martin Smith,186
Ben,186
John Rogers,186
Yang Liu,186
Amanda,186
Daniel Hernandez,185
John Ryan,185
Mark Thompson,185
Daniel Lee,185
Ryan Brown,185
Andy Smith,185
Paul Miller,185
John Carter,184
Manoj,184
Hannah Smith,184
Michael Allen,184
Tara,184
Alex Lee,184
Jasmine,184
Doug Smith,184
Daniel Martin,184
Ali,183
Mike Lee,183
David Cook,183
David Cohen,183
Eric,183
John Walker,183
Harpreet Singh,183
Diana,183
Sophie,183
Chris Wright,183
Jeff Brown,183
Mark Evans,182
James Thomas,182
Mark Lewis,182
Sean Sullivan,182
Justin Jones,182
George,182
Michael Walker,182
Mark Robinson,181
Paul Robinson,181
James Walker,181
Adam Johnson,180
Jason King,180
Sunny,180
Steve Wilson,180
Eric Lee,180
Kevin Wilson,180
Ashley,180
Dave Williams,180
Brian Kelly,180
Christina,180
James Wright,180
David Adams,180
Steven Smith,180
Chris Evans,179
Greg Williams,179
Jessica Jones,179
Daniel Williams,179
David Hall,179
Frank,179
Peter Johnson,179
John Hill,179
Justin,179
Emily Smith,179
Bobby,178
John Morris,178
Anthony,178
Sam Brown,178
Justin Johnson,177
Steve Williams,177
Jordan Smith,177
David Clark,177
David Lawrence,177
William Smith,177
Cindy,176
Deepak Kumar,176
Andrew Thomas,176
Adam Taylor,176
Jessica Smith,176
Jeremy Smith,176
John Fisher,176
Sandy,176
John Kennedy,176
David Roberts,176
Sarah Jones,176
David Campbell,176
Bill Brown,175
Sam Johnson,175
Ajay,175
David Walker,175
John Watson,175
Jeff Miller,175
Stephen Jones,175
Tom Brown,175
Kevin Murphy,175
John Murray,175
Paul Jackson,175
Brian,175
Trevor Smith,174
Tony Williams,174
Andy,174
Adam Brown,173
Aaron Brown,173
James White,173
Kevin Kelly,173
Jamie Smith,173
Amber,173
Michael O'Connor,172
Jim Smith,172
Daniel Martinez,172
Dan Brown,172
Scott Williams,172
Rachel,172
Scott Davis,172
Bob Smith,172
John Reynolds,172
Melissa,172
Karthik,172
Juan Rodriguez,171
Nathan Smith,171
Michael James,171
Adam Jones,171
Cameron Smith,171
Jennifer Lee,171
Gareth Jones,171
Vicky,171
Tim Brown,171
Paul Murphy,171
Arun,171
Michael Kennedy,171
Yang Yang,170
Kumar,170
Danny,170
Amit Sharma,170
Ken Smith,170
Scott,170
Chris Green,170
Tim Miller,170
Jessica Lee,170
John Ward,169
Emma,169
Greg Johnson,169
Michael Ross,169
John Robinson,169
Luis Garcia,168
John Edwards,168
Stephanie,168
Chris Turner,168
Anand,168
Chris Roberts,168
Rachel Smith,168
Mandeep Singh,168
John Walsh,168
Mark Allen,168
Mark Jackson,168
Matt Baker,168
Shiva,168
Eric Davis,167
Simon,167
Matthew Williams,167
Ryan Kelly,167
Tyler Johnson,167
Jake,167
George Smith,167
Anthony Smith,167
Sean O'Brien,167
Ben Williams,167
Samantha,167
Vinod Kumar,167
James Stewart,167
Ben Anderson,166
Karen,166
Keith Jones,166
Claudia,166
Patrick Murphy,166
Robert Wilson,166
Brandon Johnson,166
Chris Edwards,166
Nikki,165
Ashok Kumar,165
Chris Ward,165
David Morgan,165
Michael Anthony,165
Andrew,165
Michael Turner,165
Steve Davis,165
Marie,165
Chris Adams,165
Ben Brown,165
Chris Jackson,165
Jason Johnson,165
Paul Anderson,165
Christian,165
John Parker,164
Josh Jones,164
Sandeep Kumar,164
Martin,164
Ashley Smith,164
John Phillips,164
Angela,164
Mark Roberts,164
James King,164
Colin Campbell,164
Gina,164
Jordan,164
Chris Rogers,164
John Turner,164
Wei Li,164
Jeff,163
John Allen,163
Andrew Davis,163
Michael Becker,163
John Cooper,163
Sandeep,163
John Sullivan,163
Mark Stevens,163
Michael King,163
Scott Campbell,163
John Evans,163
Sarah Wilson,163
Babu,162
Brian Davis,162
Richard Davis,162
Justin Brown,162
John Howard,162
Carlos García,162
Jason White,162
Alexandra,162
Chris Scott,162
Andrew Thompson,162
James Scott,162
Raja,162
Tyler Smith,162
David Baker,162
David Price,162
Patrick Kelly,161
Matt Wilson,161
Carmen,161
Leo,161
Thomas Smith,161
Ian Campbell,160
Raj Kumar,160
John Mitchell,160
Paul Kelly,160
Andrew Martin,160
David Fisher,159
Matthew Taylor,159
Alex Rodriguez,159
Andrew White,159
Nick Brown,159
Jay Johnson,159
Ganesh,159
John Cox,159
Michael Schmidt,159
John Davies,159
Peter Wilson,159
Jennifer Smith,158
Prakash,158
Brian Miller,158
Brandon Williams,158
Joe Smith,158
Rita,157
Chris Murphy,157
Carlos Lopez,157
Amanda Smith,157
Christopher Martin,157
Sagar,157
Sanjeev Kumar,157
Jennifer Jones,157
Michael Stewart,156
Mark Phillips,156
Andy Jones,156
John Marshall,156
Dan Jones,156
Jimmy,156
Priyanka,156
Praveen,156
Will Smith,156
Sarah Williams,156
Robert Jackson,156
Richard Thomas,156
Steve Anderson,156
Scott Baker,155
Eric Miller,155
Chris Parker,155
Ryan Moore,155
Tiffany,155
Brian Taylor,155
Matt Thompson,155
David Turner,155
Rick Smith,155
David Phillips,155
Anonymous,155
Maya,155
Michelle Lee,155
John Cook,155
Peter King,155
Dan,155
Chris Baker,154
Christopher Williams,154
Steve Taylor,154
Nick Jones,154
Michael Hill,154
Jana,154
David Kennedy,154
Brian Wilson,154
John Bell,154
Jade,154
Daniel Miller,154
David Collins,154
Paul Baker,154
Tim,154
Ryan Murphy,154
Peter Murphy,153
Michael O'Brien,153
David Wood,153
Sarah Brown,153
Justin Williams,153
Michael Clark,153
Justin Lee,153
Anita,153
Richard Green,153
Mike Adams,153
Jim Johnson,153
Dave Thomas,152
David Martinez,152
Amandeep Singh,152
Peter Miller,152
Jennifer Johnson,152
Nick Johnson,152
Michael Wright,152
Ron Johnson,152
Christopher Johnson,152
Chloe,151
Mike Thompson,151
Keith Johnson,151
David Gonzalez,151
David Parker,151
Mark Edwards,151
Robert Clark,151
Monika,151
Michael Parker,151
Chris Cook,151
Carlos Sanchez,151
Patrick,151
Melanie,151
Ben Davis,151
Carlos Rodríguez,151
Rajesh Kumar,150
Peter Lee,150
Andrew Scott,150
Ben Thomas,150
Jose Hernandez,150
Mark White,150
Ryan Wilson,150
Chris Burns,150
Eric Jones,150
David Kelly,150
Dave Johnson,150
James Turner,149
Sanjay,149
Sunil,149
Michael Carter,149
Sanjay Singh,149
Bob Johnson,149
Scott Martin,149
Daniel Jones,149
John Hughes,149
Stephen Brown,149
Michael Young,149
Chris Clarke,149
Wei Zhang,149
David Hamilton,149
David Lopez,149
Jack Davis,149
Luke Smith,148
George Williams,148
Mia,148
Steve Martin,148
Alex Wilson,148
Adam Green,148
Eric Martin,148
Daniel Gonzalez,148
Mark Lee,148
Michael Burke,148
Priya,148
Matthew Thomas,148
Scott Jones,148
Sean Ryan,148
Patrick Johnson,148
Tom Johnson,148
Michael Evans,148
Tom Moore,148
Crystal,148
David Fox,148
Robert Moore,147
Madhu,147
Steve Moore,147
John Burke,147
Frank Smith,147
Alice,147
Michael Campbell,147
David Stewart,147
Abhishek,147
Michael Roberts,147
Sam Williams,147
Erika,147
David Murphy,147
Peter Thomas,147
Michael Wood,147
Natalie,147
Alex Garcia,146
Peter Davis,146
Michael Edwards,146
Jonathan Miller,146
Abhishek Singh,146
Matt Thomas,146
Steve Roberts,146
David Shaw,146
Bryan Smith,146
Mark Adams,146
Tom Jones,146
Scott Wilson,146
Chris Campbell,145
Katie,145
James Collins,145
Josh Taylor,145
Robert Scott,145
Josh Miller,145
Simon Smith,145
Alex Taylor,145
Paul Green,145
Alan Smith,145
James Kelly,145
Ryan Thomas,145
Rocky,145
Amit Singh,145
David Bell,145
Javier García,145
Paul Davies,145
Chris Wood,144
Michael Baker,144
David Graham,144
Abhishek Sharma,144
James Murphy,144
David Nelson,144
Kevin White,144
Ian Miller,144
Ryan Davis,144
Alex Miller,144
Robert Martin,144
Paul Walker,144
Chris Bell,144
Josh Martin,143
Kelly Smith,143
Daniel Taylor,143
Steve Clark,143
Paul Harris,143
Jeff Williams,143
Mike Green,143
Mike Taylor,143
David Howard,143
Tom Miller,143
Richard Allen,142
Adam Lee,142
David Lowe,142
John Graham,142
Laura Smith,142
Richard Lee,142
Jack Taylor,142
Andy Taylor,142
David Edwards,142
Anthony Williams,142
James Mitchell,142
Robert Allen,142
James Baker,142
Tim Wilson,141
James Murray,141
Rajkumar,141
David Morris,141
Christopher Brown,141
Sean,141
Mike Evans,141
Peter Moore,141
Chad Smith,141
Bella,141
Paul Thomas,141
Asif Khan,141
Ian Jones,141
David Murray,141
Lucky,141
David Watson,141
Lovepreet Singh,141
Alan Jones,141
Daisy,141
Daniel James,141
Matt Davis,140
Mohan,140
Petra,140
Peter Taylor,140
Kitty,140
David Cooper,140
Lauren Smith,140
Matt Anderson,140
Matthew Walker,140
Sonia,140
Aaron Williams,140
Carlos Martinez,140
Bill Williams,140
Jose Rodriguez,140
Rachel Jones,140
Keith Smith,140
Carlos Hernandez,140
Carlos Gonzalez,140
Yu Wang,140
Shankar,140
Danielle,140
Emily,140
Jim,140
Carlos Santos,140
Paul Morris,139
Matthew Jones,139
Tom Martin,139
Alex Martin,139
Ryan Young,139
Sarah Taylor,139
Andrew Moore,139
Matt Walker,139
David Rose,139
Matthew Wilson,139
Richard King,139
Andrew Jackson,139
Kyle Smith,139
Josh Brown,139
Antonio García,139
Paul Lewis,139
Brian Anderson,139
David Cox,139
Steve Wright,138
Jane,138
Charlie Smith,138
Matt King,138
Emma Smith,138
John Palmer,138
Aaron Johnson,138
Amy Smith,138
Michael Bell,138
Robert Hill,138
Vishnu,138
Jason Thompson,138
Carlos Sánchez,137
Mark Nelson,137
Tom Anderson,137
Ryan Lee,137
William Brown,137
Kuldeep Singh,137
Bill Smith,137
Robert King,137
Ben Miller,137
Ben Thompson,137
Veronica,137
Naveen,137
Rohit,137
Andrew Taylor,137
Pradeep,137
Steve Harris,137
Johnny,137
John Nelson,137
Trevor Jones,137
Mike Thomas,136
Lei Zhang,136
Anastasia,136
Steve White,136
Alexis,136
John O'Connor,136
Joe Williams,136
David Holmes,136
Robert White,136
Chris Davies,136
Rob Jones,136
Michael Mitchell,136
Mike Murphy,136
Anil,136
Carlos López,136
Jeff Jones,136
Dan Miller,136
Michael Adams,136
Chris Morris,136
Greg Jones,136
David Gordon,136
Anthony Davis,135
Sean Williams,135
Santosh,135
Paul Davis,135
Anthony Brown,135
Sarah Johnson,135
Dave Roberts,135
John Fox,135
James Cooper,135
David Richardson,135
Simone,135
Marina,135
Chris Ryan,135
Richard White,135
Jessica Taylor,135
Jonathan Taylor,135
Tom Evans,135
Michael Murray,134
Sean Davis,134
John McCarthy,134
Karen Smith,134
Kevin Miller,134
Brian Moore,134
Carlos González,134
Michael Morris,134
Daniel García,134
Samantha Smith,134
Michael Harrison,134
Ryan Taylor,134
Jason Anderson,134
Steven Brown,134
Bruno,134
Joe Brown,134
Russell Smith,134
Mike Scott,134
David Foster,134
Jack Martin,134
Tony Wilson,134
James Morris,133
Lauren,133
Alex Scott,133
Julie,133
Jim Miller,133
Paul Roberts,133
Li Li,133
Chris Phillips,133
David Hernandez,133
Jason Jones,133
Ian Wilson,133
Jeremy Johnson,133
Andy Lee,133
David Mason,133
Jack Kelly,133
Tim Williams,133
Robert Thomas,132
Kyle,132
James Edwards,132
Alex Johnson,132
John Butler,132
John Harrison,132
Ram,132
David O'Brien,132
Chris Nelson,132
Rebecca,132
Venkat,132
Ryan Anderson,131
Michael Klein,131
John Wood,131
Ivan Ivanov,131
Matt Robinson,131
Carlos,131
Zach Smith,131
Charles Williams,131
Chris Bailey,131
Richard Thompson,131
Lee Smith,131
Kevin Anderson,131
Jake Smith,131
Michael Walsh,131
John Foster,131
Patrick Williams,131
Morgan Smith,131
Michael Bennett,131
James Jackson,131
Andrew Kim,131
Andy Brown,131
Paul Lee,131
David Cole,131
Rakesh,131
Robert Thompson,131
Anthony Johnson,131
Mike Moore,130
Barbara,130
Elizabeth Smith,130
Paul Stewart,130
Scott Walker,130
John Kim,130
Bob,130
Jack White,130
David Carter,130
Amy,130
Tim Davis,130
Michael Martinez,130
Jamie,130
David Kim,130
Bill Miller,130
Stephen Johnson,130
Joshua Johnson,130
David Clarke,130
Joe Johnson,130
Carlos Flores,130
Jacob Smith,129
David Schwartz,129
Mike King,129
Mike Roberts,129
Surya,129
Gary Brown,129
Josh Williams,129
Dave Wilson,129
Michael Levine,129
Shane Smith,129
Ian Johnson,129
Alex Moore,129
Amritpal Singh,129
Ryan Thompson,129
John Bennett,129
Rose,129
Andrew Robinson,129
Michael Jackson,129
Jordan Miller,129
Matt Hill,129
Victor,128
Simon Jones,128
Sam Miller,128
Yan Li,128
Ian Brown,128
Kevin Clark,128
Tony Martin,128
Michael Phillips,128
Michael Lopez,128
Mario,128
John Richardson,128
Jackie,128
Rob,128
Kate,128
Yi Wang,128
John Ford,128
Mike Hall,128
Mike Jackson,128
Tom Kelly,128
Richard Hughes,128
John James,128
Nick Walker,128
Carlos Torres,127
James Robinson,127
Andrew Young,127
Nathan Brown,127
Charles Johnson,127
Brian Thompson,127
Daniel Wilson,127
Andrew Hall,127
Lei Wang,127
David González,127
Nancy,127
Brian King,127
Michael Stone,127
Sarah Walker,127
Jennifer Brown,127
Jose Garcia,127
Yang Li,127
Jorge García,127
Kamal,127
Josh Johnson,127
Luis Rodriguez,127
John Alexander,126
Bill White,126
Andrew Harris,126
James Alexander,126
David Bennett,126
Brian White,126
Rahul Kumar,126
David Ward,126
Jing Li,126
Matt Harris,126
Scott Thompson,126
Mark Campbell,126
Ying Wang,126
James Morgan,126
Lucas,126
Greg,126
Jack Miller,126
Sanjay Kumar,126
John Russell,126
John Bailey,126
Robert Walker,126
Jason Martin,125
Jessica Williams,125
Jeff Davis,125
Christopher Lee,125
Candy,125
Robert Campbell,125
John Clarke,125
Jeff Clark,125
Kevin Scott,125
Alex White,125
Anthony Jones,125
Steve Thomas,125
Gaurav Sharma,125
Derek Jones,125
Dinesh,125
John McDonald,125
Jeff Taylor,125
Prince,125
David García,124
Dave Taylor,124
Gary Jones,124
Sean Lee,124
Tom Wilson,124
Mike Walker,124
Ian Anderson,124
Monique,124
Vishal,124
Michael Price,124
Tony Garcia,124
David Gray,124
Michael McCarthy,124
Michael Gordon,124
Carlos Moreno,124
Luna,124
Carlos Ramirez,124
Larry Smith,124
Coco,124
Chris James,124
David López,124
Chris Mitchell,124
Karina,123
Paul Allen,123
David Nguyen,123
Dave Anderson,123
Matthew Miller,123
David Russell,123
Srinivas,123
Mona,123
Chris Cole,123
Jonathan Davis,123
Gurwinder Singh,123
Richard Martin,123
Christopher Moore,123
Robert Wright,123
Paul Harrison,123
James Ryan,123
Praveen Kumar,123
Eric Thompson,123
Tony Jones,123
Charles Smith,122
Charles Miller,122
James Roberts,122
Bob Jones,122
Michael McDonald,122
David Warren,122
Mark Murphy,122
Jennifer Wilson,122
Joe Wilson,122
Matt Green,122
Harry,122
Tom Taylor,122
Christine,122
Luis Moreno,122
Ben Harris,122
Paul Young,122
Jing Zhang,122
Nathan Jones,122
Tom Wright,122
Adam King,122
Chris Carter,121
Jonathan Martin,121
Brian Hall,121
Harish,121
Adam Miller,121
Bob Anderson,121
Tim Martin,121
James Phillips,121
Vikram Singh,121
Sam Taylor,121
Jeff Allen,121
Kevin Jackson,121
Rohit Kumar,121

In [0]:
%sql SELECT B.primaryName, COUNT(*)
FROM gold.names_titles AS A,
  gold.names_titles AS B
WHERE A.primaryName = "Kevin Bacon"
AND B.primaryName <> "Kevin Bacon"
AND A.tconst = B.tconst
GROUP BY B.primaryName
ORDER BY COUNT(*) DESC

primaryName,count(1)
Mik Glaisher,4
Stephen Fellows,4
Andy Peake,4
Jim Scharf,3
Bill Jones,2
Mike O'Neill,2
Corey Rich,2
Robert Bluemke,2
Gary Cobb,2
Tim Scott,2
Gina Pearl,2
Jesse Evans,2
John McCarthy,2
Gene Miller,2
Dan Long,2
Craig Cleary,2
Tim Corbett,2
Matt Powell,2
Carl Radle,1
Marty Grebb,1
Emillie Key,1
The Chevalier Brothers,1
Leon Wilkeson,1
Wendy Smith,1
Sharks,1
Time Zone,1
Roger Newell,1
Rosa Rudnicka,1
Neil Brewer,1
Human Sexual Response,1
Working Week,1
Dini Lamot,1
Steve Farr,1
Be-Bop Deluxe,1
Ollie Halsall,1
Brinsley Schwarz,1
Annabel Lamb,1
José van Iersel,1
Fanny,1
Peter Kirtley,1
Mick Pearl,1
Dave Lloyd,1
Medicine Head,1
Charlie Harrison,1
Morris Pert,1
Carmelo Luggeri,1
Micky Jones,1
Tatsuji Kimura,1
Trevor Williams,1
Robert Vincent,1
Tygers of Pan Tang,1
Hans Vandenburg,1
Fabulous Poodles,1
Judi Pulver,1
Ox,1
Erik Russell,1
John Gifford,1
The Racing Cars,1
Hans Waterman,1
The Faces,1
Tasavallan Presidentti,1
Natural Acoustic Band,1
Roy Young,1
Fashion,1
Rich Gilbert,1
Billy Powell,1
Homesick James,1
Steve Hackett,1
The Bloodfire Posse,1
Jason & the Scorchers,1
Steve Ellis,1
Tony Hughes,1
Trace,1
The Woodentops,1
Gavin Hodgson,1
Liz Kershaw,1
Hot Tuna,1
Tom Corcoran,1
David Sinclair,1
The Associates,1
Half Man Half Biscuit,1
Cousin Joe Pleasant,1
Al Di Meola,1
Paul Brett,1
The Baker-Gurvitz Army,1
Greenslade,1
The Weather Prophets,1
The Colourfield,1
Frankie Paul,1
King,1
Dick Morrissey,1
Jean-Jacques Kravetz,1
James Litherland,1
Bob Burns,1
It Bites,1
Percy Jones,1
Hudson Ford,1
Sean Tyla,1
The Mystery Girls,1
Clive John,1
Robyn Hitchcock and the Egyptians,1
Original Mirrors,1
Tina O'Neill,1
David Hepworth,1
Colin Strong,1
Graham Deakin,1
Little Steven and the Disciples of Soul,1
Madeleine Pittet,1
Lieber Stoller,1
Michael Chapman,1
The Movies,1
Hipsway,1
Tony Connor,1
Martin Stephenson,1
John Goodsall,1
Twelfth Night,1
It's Immaterial,1
The Screaming Blue Messiahs,1
Dave Lambert,1
Persia Numan,1
Danny McIntosh,1
Calvin Hayes,1
Sandy West,1
Eamon Carr,1
Tom Barlage,1
Raymond Froggatt,1
Steve Parry,1
Huw Lloyd Langton,1
Alice Stuart,1
Rock & Roll Allstars,1
Stuart MacKillop,1
Cook Da Books,1
Herman Brood & His Wild Romance,1
Fiat Lux,1
Landscape,1
Keith Gemmel,1
Stackridge,1
The Motors,1
Andrew Coggins,1
Alison Statton,1
Matthew Seligman,1
Daryl Stuermer,1
Ro Newton,1
Floy Joy,1
The Redskins,1
The Sound,1
Stephen Irvine,1
Mollie Marriott,1
Barry De Souza,1
Judd Lander,1
Graham Broad,1
The Long Ryders,1
Charley Charles,1
Alma Player,1
Jeff Berlin,1
Henry McCullough,1
Roye Albrighton,1
Harvey Andrews,1
Kissing the Pink,1
Keith West,1
Secret Affair,1
Maggie Dunne,1
Russell Javors,1
John Giblin,1
Mike Edwards,1
Latin Quarter,1
Michael Appleton,1
Suzanne Smith,1
Martin McAloon,1
Mick Cater,1
John Walters,1
Nine Below Zero,1
Gary Fletcher,1
Mark Ellen,1
John Turnbull,1
Johnny Fean,1
German Gonzales,1
Upp,1
Neil Conti,1
Chris Maclachlan,1
Return to Forever,1
Ant Glynne,1
Leather Nun,1
May Miller,1
Jimmy Cameron,1
Francisco Sancha,1
Tony Stevens,1
Dave Kelly,1
Crawler,1
Herbert Stehr,1
Keith Mulholland,1
Allez Allez,1
Faith Brothers,1
Richard Williams,1
Peter Wolbrandt,1
Bryn Haworth,1
Green on Red,1
Blue,1
Ashley Holt,1
Lawrence Donegan,1
John Evan,1
Jeff Baker,1
Ronnie Leahy,1
Jimmy Lockhart,1
The Inmates,1
David G. Croft,1
Steve Simpson,1
Magna Carta,1
Vickie Perks,1
Sarah Parkinson,1
Swans Way,1
Casey Cameron,1
The Monochrome Set,1
Andy Diagram,1
The Pontiac Brothers,1
Ed Geil,1
Tubeway Army,1
Geoff Dugmore,1
Girl,1
Chris Masuak,1
Vella Cameron,1
John Goldrosen,1
Tommy West,1
John Burrowes,1
Howard Werth,1
Baz Watts,1
Otway & Barrett,1
Big Sound Authority,1
Leslie Stephenson,1
John Ware,1
Doug Stegmeyer,1
Charles O'Connor,1
Ernest Cate,1
Beth Key,1
Neil Clark,1
The Jags,1
Chris Harley,1
The Bluebells,1
New Musik,1
Pip Foster,1
Jaki Whitren,1
Winston Hislop,1
Clifford T. Ward,1
Bobby Tench,1
Colin Tully,1
John Dunsterville,1
Trevor Dann,1
Ric Sanders,1
Joe Partridge,1
Luther Grosvenor,1
Chester Thompson,1
Rab Noakes,1
Saga,1
Dave Evans,1
The Winterbabies,1
Lone Star,1
The Kane Gang,1
Sad Café,1
Andy Ellison,1
Annette Peacock,1
Andy Kershaw,1
Wildwood Kin,1
Bob 'Willard' Henke,1
Jonathan Kelly,1
Martin Gordon,1
Rain Parade,1
Holly Vincent,1
Planxty,1
Jamie Oldaker,1
The Passions,1
Reg Brooks,1
Hughie Flint,1
Dave Jackson,1
Vinegar Joe,1
Jo Dunne,1
Windle Davis,1
Robert King,1
Earl Cate,1
Bob Weston,1
Chris Cutler,1
The Country Gazette,1
Allan Holdsworth,1
Au Pairs,1
Hellmut Hattler,1
Chris Parren,1
The Tourists,1
Meghann Loney,1
Light of the World,1
George Cummings,1
Heavy Metal Kids,1
Ken Berry,1
Mike Absalom,1
Jeremy Meek,1
The Models,1
Henry Gross,1
Juris Eksts,1
Andrew Brett,1
Jennifer James,1
Lindsay Curtius,1
William MacCready,1
Terra Johnson,1
Margaret Mazzei,1
Evan O'Neill,1
Jason Marshall,1
Debra J. Olchick,1
Waltier Blocker,1
Desiree Jones,1
James 'Otis' Mayfield,1
Michael Staranowicz,1
Peter Wilson,1
Monica Gonzalez,1
Marvet Britto,1
Don Greenleaf,1
Nicole Kassell,1
Mark Westman,1
Brook Lenfest,1
Kendra D. Wadsworth,1
Hally McGehean,1
David Brandon,1
Mark Shandley,1
Ryan Wachter,1
Amy Mayfield,1
James Sloane Jr.,1
Jared Springer,1
Kyra Sedgwick,1
Floriane Miniscloux,1
Lauren Almasy,1
Charles Gabriel,1
Stephen Beatrice,1
Robert Johnson,1
Patrick Bolger,1
Thaddeus Weintzen,1
Joey Hazinsky,1
Missy Moyer,1
Shannon Stewart,1
John Tarlini Jr.,1
The Bacon Brothers,1
Valerie Hoffman,1
Yasiin Bey,1
Kenneth Cue,1
William M. Hamilton Jr.,1
Marin Sander-Holzman,1
Candice Williams,1
Wayne Clemons,1
Susan Gabbay,1
Katie R. Dailey,1
Âsa Håkansson,1
Kevin Rice,1
Amy Silverman,1
Anthony Giunta,1
Jessica Nagle,1
Paul S. Magee,1
John Keller,1
Patrick Bentley,1
Damon Dash,1
Gabriella Palumbo,1
Samantha Ronson,1
David Schwartz,1
Florence Holdeman,1
Aunt Dot,1
Laura Galli,1
Dawn Lenfest,1
Doreen S. Oliver-Akinnuoye,1
Nicole Gibson,1
Ruben O'Malley,1
Colin Helb,1
Syreeta Mccoy,1
Robert Hall,1
Keith Yurevitz,1
Jennifer Russomanno,1
Erika S. Byard,1
Civilla Martin,1
Charles Washington Jr.,1
Jay Stuart,1
Nicole Marsella,1
Barbara Muehleib,1
Rissi Palmer,1
Steven Fechter,1
Pamela Thompson,1
Matthew Dicks,1
Gil Richardson,1
Jason Block,1
Eve,1
Buffy Lawson,1
Jennifer Schoenewald,1
Andy Sforzini,1
Joyce Werner,1
Jay C. Stuart Jr.,1
Andrew Cinquino,1
Clara Hopkins Daniels,1
Carolyn Holloway,1
Kenneth Min,1
Monique LaMontagne,1
Spencer Ross,1
Raushanah S. Shamsid-Deen,1
Eva N. Marinakis,1
Steven Holtzman,1
Maya Choldin,1
Princess Idia Gamble,1
Carlos Leon,1
Ashley C. Coombs,1
Benjamin Goldberg,1
Jaqueline Noel,1
Edward Spencer,1
Sara Devine,1
Robert Tyler,1
Jordan Gable,1
Liam Daniels,1
Gerald Ehresmann,1
David Robinson,1
Laila Kjoersvik Swanson,1
Timothy Weston,1
Ronald Brescio,1
Chong K. Pak,1
Eileen Marks,1
Hannah Pilkes,1
Jonathan Martofel,1
Robert J. Rocco,1
Maribeth Rubenstein,1
Nana Ashong,1
Joe Caterini,1
Tim Susco,1
Lee Daniels,1
Jennifer Pope,1
Daniel Wiener,1
Michael Mezaros,1
Mike Nava,1
David Butler,1
Echo Andersson,1
Brendon Bates,1
Dodie Graham McKay,1
Tim Morin,1
Ryan Hanson,1
Rufus,1
Jared Given,1
Nic Kriellaars,1
Ken Janssens,1
Julian Kapadia,1
Crickett Cote,1
Bryan L. Verot,1
Jennie Eng,1
Rashaan Kearse,1
Andre Spencer,1
Andrea Nilosek,1
Alexi Silverman,1
David Hardman,1
David Lovejoy,1
James Daw,1
Sally Wood,1
J.P. Guimont,1
Robert Fiske,1
Landon Lake,1
Robert Sylvain,1
Kim Sprague,1
Shauntelle George,1
Randy Gambill,1
Keaton Fish,1
Joel Osgood,1
Ashley 'Crickett' Cote,1
Tommy Castellanos,1
Joe Brunette,1
Helen Bellafiore,1
Maclean Fish,1
Jan Skene,1
Brooke Rochon,1
Autumn Crook,1
Jaydee-Lynn McDougall,1
Meagan Moses,1
Marissa Ronca,1
BJ Verot,1
Heather Luckman-Beckstead,1
Bess Welden,1
Brittni Moore,1
Drew Scurfield,1
Rob Cortes,1
Casey Turner,1
Renata Daoud,1
Emily Bernhard,1
Jilian Gersten,1
Nate Meyer,1
Carmen Caceres,1
Jon Berg,1
Ophelie Petit,1
Steven Webb,1
Devin Guimont,1
Josh Taylor,1
Mike Savasuk,1
Jennifer Taxel,1
Maureen Butler,1
Ernie Bonelli Jr.,1
Dean Pitchford,1
Annette Cirillo,1
Valarie Wise,1
Sawyer Barth,1
Niraj Bhatia,1
Moving Pictures,1
Ian Christman,1
Dottie Vaughn,1
Danny Walton,1
Danielle Vera,1
Jim Steinman,1
Alan Haufrect,1
Tom Counts,1
Dennis Rice,1
Linda MacEwen,1
Bonnie Tyler,1
Kelly Griffin,1
Evan Schafer,1
Russell Jeffcoat,1
Ken Counts,1
David Lockwood Andrews,1
Rory J. Roche,1
Samuel O'Sullivan,1
Lynne Marta,1
Kevin Schmidt,1
Neil Cuthbert,1
Tim Buss,1
H. Denise Rivers,1
Colin Alexander,1
Weston Currie,1
Eric Salamone,1
Valerie Corelli,1
Jett Steiger,1
To Lee,1
Ronnie Kramer,1
Mimi Broadhead,1
Jan Illing,1
Adea Lennox,1
Lewis J. Rachmil,1
Chuck Cirino,1
Zoran Hochstätter,1
Claire Entrup,1
L. Andrew Stone,1
Lane Parrish,1
Ed Sullivan,1
Dario Saraceno,1
Leon Izsak,1
Meghan Broadhead,1
Julianna Austin,1
Gregory Scherick,1
Karla Bonoff,1
Wayne Brown,1
David Richard,1
Robert Yapkowitz,1
Jessica Collins,1
Stephen Pagano,1
Stephanie Farah,1
Brett Gehrke,1
Adrian Carter,1
Harold Rabuse,1
Sherri Scott,1
Michael Norquest,1
Bill Wolfer,1
Oscar Rowland,1
Chris Penn,1
Keith Olsen,1
Jane Feather,1
Stan Bielowicz,1
Lorenzo Beronilla,1
Sammy Hagar,1
Frances Lee McCain,1
Willard Stephens,1
David Cann,1
Robert Allen,1
Arthur Rosenberg,1
Lester Tremble,1
Charles Graves,1
Danny Rooney,1
Daniel K. Moore,1
Bill Johnson,1
Don Shelley,1
Leslie Rosenthal,1
Ken Kemp,1
Barbara Lampson,1
Kathleen Kennedy,1
Rachel Ward,1
Nadia Collado,1
Ron Pearson,1
Keith Marlin,1
Jordan P.H. Stein,1
Carol Rees,1
Gene Pack,1
Hayden Oliver,1
David Valenza,1
Monica M. Da Silva,1
Lou Gramm,1
L. Robert Stanfield,1
Mattheau O'Brien,1
Pete Zickus,1
Frankie Banali,1
Esther Vivante,1
Lorraine Watson,1
Terry Tyroch,1
Marcia Dangerfield,1
Blake Wilcox,1
Craig Zadan,1
Jim Williams,1
Andrew Banks,1
Steve Mitchell,1
Lana Kim,1
Sam Edelman,1
J. Suzanne Fish,1
Laura Piccirillo,1
Eric Carmen,1
Carmen Trevino,1
Terri Gay Ulmer,1
Kenny Loggins,1
Tom Snow,1
Joey Alfieris,1
Dan Bida,1
Ray Ellis,1
Timothy Scott,1
John Perryman,1
Dana Lockhart,1
Kim Graham,1
Greg Meola,1
Edward Parks,1
John Laughlin,1
Tony Trimarco,1
Tony Cavazo,1
Deniece Williams,1
Frawley Becker,1
Greg Reim,1
Sam Dalton,1
Robert Bradshaw,1
Jamie Flanagan,1
Mike Reno,1
Mike Maguire,1
Shalamar,1
Cockroach Bob,1
John Bishop,1
Becky Mancuso-Winding,1
Joseph Visconti,1
Norm Prescott,1
Jay Bernard,1
Tom Scope,1
Melissa Renee Graehl,1
Al Overton Jr.,1
Bruce Meade,1
Johann Bley,1
Trey Hock,1
Emily Schubert,1
Jay Bentley,1
Rob Watson,1
Robert E. Warner,1
Barbara L. Ayers,1
Owen Campbell,1
Graham Lewis,1
Douglas Dirkson,1
Barton Kent James,1
Clair E. Leucart,1
Kim Jensen,1
Russ McGinn,1
Anni Krueger,1
Luke Piotrowski,1
Kevin DuBrow,1
Mary Elizabeth Haynsworth,1
Adam Schaffer,1
Lori Singer,1
John Boylan,1
Peter Tramm,1
James Graves,1
Lynda Webb,1
Heather Locklear,1
Philip Jones Jr.,1
Ryan Dickie,1
Jackie Brummer,1
Rachel Lennox,1
Matt Fleischmann,1
Bill Eudaly,1
Bruce Gilbert,1
Richard Blurr,1
Philip H. Ashley,1
J. Paul Broadhead,1
Timothy Birch,1
Michael Gore,1
Joan S. Aceste,1
Ann Nickinson,1
Jim Moores,1
Daniel Melnick,1
Wire,1
Rommel Genciana,1
Nikita K. Carpenter Jr.,1
Kortnee Simmons,1
Devan Maura Saber,1
Elston Williams,1
Derek DeVoe,1
Robert Troeller,1
Esha Kallianpur,1
Alfredo Romeo Suarez,1
Patricia Gallio,1
William Crouse,1
Carlos Cavazo,1
Ralph Pace,1
Cathy Schellhorn,1
Kevin Phillips,1
Ethan Botwick,1
David Oliver Pfeil,1
Jim Youngs,1
Lucas McGowen,1
Dan Burks,1
John Mellencamp,1
Chris O'Connor,1
Philip Aitken,1
Jasmine Ballou Jones,1
Eva Michon,1
Stan Gilbert,1
Colin Newman,1
Dario Bigi,1
Justin Rose,1
Dale Wolfield,1
Harvey Citron,1
Katie Lobel,1
Fred Yohe,1
George Duke,1
Eli Born,1
Michael Henshaw,1
Brian Zickus,1
Ben Collins,1
Charles Mitchell,1
Raphael Camacho,1
Jamie Gruber,1
Mary Ethel Gregory,1
H.E.D. Redford,1
Lynne Taylor-Corbett,1
Paul Godwin,1
Hayley Witt,1
Ben Frost,1
Garland Berenzy,1
Robert Hanson,1
Elizabeth Cappuccino,1
Stephan Harris,1
Vincent Altamore,1
Dawn Wolfe,1
Primitive Radio Gods,1
Ed Yonaitis,1
Ron Hobbs,1
Richard Graves,1
Traci Carlson,1
Chris Krueger,1
Grant Morris,1
Chuck Gaylord,1
Franklin Vaughan,1
Colton Somavia,1
The Comsat Angels,1
Reese Peters,1
David Handman,1
Donald Hauer,1
William Hall,1
Victoria Rose,1
Skot Garrick,1
Bad Religion,1
Michael Maslansky,1
Mary Swanson,1
Spencer Henderson,1
Arnie Holland,1
Kevin Callahan,1
Genn Shaughnessy,1
Max Talisman,1
Muffy Haggerty,1
Cameron Lamb,1
Irma de Wind,1
Elizabeth Gorcey,1
Michael Telmont,1
Murray Schwartz,1
Richard R. Robinson,1
Tom Moye,1
Lee De Carlo,1
Stephen Rathier,1
Eros Cartechini,1
Emily Erhart,1
Renee Vandale,1
Jessica Gasson,1
Adam Camara,1
Monique Foreste,1
Brian Wiacek,1
Adam Brooks,1
James Dutch,1
Alexandra Garrido,1
Danny Chodirker,1
Laura Veirs,1
Kevin Ascolillo II,1
Stephanie Thiel,1
Mihir Patel,1
Josh Kleinman,1
Leonard Slatkin,1
Zac Clark,1
Seth Silberfein,1
Will Hart,1
Jon'Nathon Stebbe,1
Donald J. Tucker,1
Dustin Holloway,1
Ruby Masters,1
Wyatt Gulash,1
Bryan Sarmiento,1
Jack Armellin,1
Jasmine Mae,1
Suzie Ford,1
Jim Howell,1
Taylor Locke,1
Polly Cutter,1
Anthony J. Haidar,1
Christina Errante,1
Sean T. Boyle,1
Matthew Kennedy,1
Warren Ellis,1
Lily Chee,1
Evan Guidera,1
Telashae Mckithen,1
Jason Sarrey,1
Simon Estes,1
Richard P. Dipietro,1
Renzo Castro,1
Katherine Ciarlo,1
Cash E. Campbell,1
Joshua Heida,1
Catalin Patrichi,1
Eli Koskoff,1
James Ferreira,1
Chris Dimoulas,1
Victoria Guenier,1
Scott Baker,1
Elaina Levy,1
Dora Woodrum,1
Tess Henley,1
Rundfunkchor Berlin,1
Elizabeth Sussman,1
Linda Peckel,1
Max Kuehn,1
Meredith Sweeney,1
Jen Kowalchuk,1
Norman Orenstein,1
Morgan Davis,1
Nicole Katz,1
Muhshin Khan,1
Tori Feinstein,1
Paul Joyce,1
Andrea Alamo,1
Amyrh Harris,1
Camilla Skalski,1
Sheila Campbell,1
Erin Russell,1
Alex McLellan,1
Shan Jin,1
Andrew Thomas,1
Matthew DiLorenzo,1
Turner Curran,1
Nancy Barry,1
Darcy Hicks,1
Jacob Garfinkel,1
Diane Curry,1
Nehemiah Brown,1
Christopher Sorelle,1
Roberta Alexander,1
Ryan Stevenson,1
Alexis Atkinson,1
Courtney Feemster,1
Sarah Koskoff,1
Unicity,1
Claudio Simonetti,1
S. Kennedy,1
Sal Barra,1
Samantha Hill,1
Nick Gifford,1
Brandon Schwartzel,1
Trevor Tuminski,1
Kevin Anderson,1
Vercetti Technicolor,1
Nicky Cruz,1
Alexander Peters,1
Nik Shpilberg,1
Jynx Vandersteen,1
Larry Thompson,1
Abby Patrick,1
Glenn Schloss,1
Joe Koplowitz,1
Paten Hughes,1
Bryan Webb,1
Redding Hunter,1
Oliver Lanzenberg,1
Jesse Rudoy,1
Ebonee Noel,1
Layla Khoshnoudi,1
Ronald Sargo,1
Vanja Jeftic,1
Keith Poulson,1
Louis Balletta,1
Helen Rogers,1
Andy Schuyler,1
Ian Davis,1
Justin Fischer,1
Chadd Harbold,1
Ben Perry,1
Kiley Olsen,1
Maxwell Barlow,1
Brian Quill,1
Lauren Molina,1
Alyssa Ann Bono,1
Salvatore Esposito,1
Emily McKinley Hill,1
Bumi Hidaka,1
Jacqueline Tosline Davis,1
Samantha Sheppard,1
Evan Sacks,1
David Vogt,1
Kevin Flatow,1
John T. Lee,1
Yancy Calzada,1
J. Chan Claggett,1
John Clark Matthews,1
David Spencer,1
David B. Vallone,1
Jennifer McGaffigan,1
Scot Shinderman,1
Skunk Anansie,1
Eric Rigney,1
Donovan Terranova,1
Andrew Goldstein,1
Shari Nicotero,1
Lincoln Simonds,1
Stacy Lumbrezer,1
Andrea Horta,1
Michelle St. Clair,1
Anthony T. Pennello,1
Olivia Harris,1
Wade Wilson,1
Bradley Clouse,1
Jimmie F. Skaggs,1
Scott D. Davis,1
Robert Troy,1
Adam Nelson,1
Don Kincade,1
Christine M. Michalosky,1
Nicholas Grieco,1
Blu Murray,1
Laurent Charbonnel,1
Bonnie E. Mackie,1
Greg Brickman,1
Ed O'Keefe,1
Jason Schleifer,1
Matthew M. Robinson,1
Jennifer Juen,1
Rod Paul,1
Derek Carlson,1
Dennis Lehane,1
Vicky Kwan,1
Daniel J. Cook,1
Whit Eldridge,1
Kevin Wilcox,1
Alison Mork,1
Walt Martin,1
Barry Walton,1
Will Lyman,1
Patrick Hollenbeck,1
Arnaud Peiny,1
Jeff Ziter,1
Carmen Flores De Tanis,1
Charley Broderick,1
Shellaine Corwel,1
Nick Bali,1
Kelly Wilcox,1
Marty Holthaus,1
Eric DeYoung,1
Glen R. Feldman,1
Jim Gordon,1
Traci Tateyama,1
Benjamin Lishka,1
Kyle Martin,1
Ken W. Ballantine,1
Dominick Cecere,1
Susan Grennan,1
David W. Nims,1
Tim Roche,1
Bob Kaiser,1
Spencer Treat Clark,1
Kenny Sanford,1
Tasso Lappas,1
LaNelle Mason,1
Stephani Hunter,1
David A. Goodman,1
Juliana Hatfield,1
Charles Saldana,1
Matthew C. May,1
Jeff Deyoe,1
Andrew Mumford,1
Marvin Jones,1
Elizabeth Metzker,1
Mary Biondo,1
Gokhan Kisacikoglu,1
Ben Hayden,1
Matt Byrne,1
Damon Bard,1
Christine Sugrue,1
Eric Armstrong,1
Andrew W. Marlowe,1
Charles W. Wayt,1
Steve Lonano,1
Aaron Katz,1
Mark Fitzgerald,1
Matthew Dettmann,1
Sissy Grover,1
Michael Bilog,1
Kirk D. Hansen,1
Stan Parks,1
William Opdyke,1
Robin Thompkins,1
Axel Dirkson,1
Joel Renfro,1
Mark Lambert,1
Shannon Curfman,1
Phil Notaro,1
Mark Lyon,1
Rome Duval,1
Henry Bumstead,1
Clint Hanson,1
Allen Ruilova,1
Stephanie Vendrell,1
Mable Lawson-McCrary,1
Patrick Shea,1
Darius A. Sultan,1
Tim Robbins,1
Mel Dunson,1
Chris Yee,1
Michael Kabella,1
Kenny Gallagher,1
Jim Smith,1
John Musumeci,1
Phred Lender,1
Paolo Costabel,1
Donald Pennington,1
Marcia Gay Harden,1
Bruce Ricker,1
M. Scott McKee,1
Zac Jackson,1
Edward Gould,1
Justine Sagar,1
Sean Penn,1
Todd W. Spencer,1
Lane Combs,1
Mary Ellen James,1
Karri Mayo,1
John R. Shourt,1
Joel Cox,1
Mike Rutgard,1
Michael Hobbs,1
Paul Jessel,1
Aaron Florez,1
Patrick Cohen,1
T. Daniel Scaringi,1
Matty Blake,1
Mark Hall,1
Chris Arreola,1
Lucy Coldsnow-Smith,1
Yvette Marxer,1
Keith B.C. Gordon,1
Jenniphur Ryan,1
Dan Gindroz,1
Constance Dennerline,1
Shô Igarashi,1
Ken Bellanca,1
Kurosh ValaNejad,1
Allen Mansour,1
David A. Schreiber,1
Pablo Espinosa,1
Kandece Brown,1
Laurence Fishburne,1
Ali Derakhshan,1
Stanley Brossette,1
Michael Haboush,1
Michael Roccuzzo,1
Jason Soles,1
Phyllis Huffman,1
Michael R. Rabanera,1
Patrick G. Brady,1
Ralph Sevazlian,1
Brian Keeney,1
Eric Ingerson,1
Melissa Cummins Lorenz,1
Dan Ziegler,1
Michael Cipriano,1
Robert Cable,1
Beth Carey,1
Dave Zee Garison,1
Darren Lurie,1
Dennis Webb,1
Brian Thomas Nist,1
Mark Siew,1
Tommy Holmes,1
Jon Tanimoto,1
Scott Kravitz,1
Mark Richardson,1
Michael Muscarella,1
Benny McNulty,1
Kevin Watkin,1
Doug Wall,1
José Ramón Rosario,1
John Schmidt,1
Ken Dubinski,1
Lloyd Bernberg,1
Betsy Nofsinger,1
John Schacht,1
Kyle Eastwood,1
Don Howe,1
Daniel Ma,1
Brenda Vivian,1
Greg Manion,1
Martin Ivor Kent,1
Karen Spangenberg,1
Matthew P. Welker,1
Bruce Navsky,1
Adrian Gorton,1
John Lacy,1
Gloria D'Alessandro,1
Mary Randle,1
John Lundberg,1
Anthony LaMolinara,1
Juanma Fernández-Paris,1
David Worman,1
Phil Culotta,1
Tim Bird,1
Greg Newman,1
Min-Zhi Shao,1
Boston Symphony Orchestra,1
Thomas Hollier,1
Jim Wardell,1
Cass Lewis,1
Nathan Eriksen,1
James Callanan,1
Stephen S. Campanelli,1
Cayden Boyd,1
Frank Petzold,1
Gail Wise,1
Jack G. Taylor Jr.,1
Dominic V. Ruiz,1
Salvy Maleki,1
Todd Durboraw,1
Theodore Suchecki,1
Jenny O'Hara,1
Ann Culotta,1
Katherine Scheid,1
Kenneth J. Silverstein,1
Susan Willis,1
Mark Schouten,1
Judie Hoyt,1
Steve Altes,1
Dee Storm,1
Juno J. Ellis,1
Katie Carroll,1
Patrice d.S. Saenz,1
Carol Corwin,1
Nadia Randazzo Bombino,1
Peter Palombi,1
Jamal Sullivan,1
Brian Pierson,1
Lewis Burnett,1
Tony Buffa,1
Luke Ramsey,1
John Vincent Mason,1
Stephani Ritenour,1
Benjamin C. Robertson,1
Chris Russell,1
Jody Steiner,1
Ian Slater,1
Michael McGovern,1
Deborah Hopper,1
Joshua Geisler-Amhowitz,1
Ross Dunkerley,1
Robert L. Manning,1
Mike Gentile,1
Scott E. Anderson,1
John McGee,1
Arthur Sutherland,1
Cynthia Aragon,1
Craig Pettigrew,1
Roger Sassen,1
Brent Armstrong,1
Rod Ibanez,1
Merie Weismiller Wallace,1
John McLaughlin,1
Andrew Mackin,1
John Haselbusch,1
Tish Johnson,1
Shayna Ritenour,1
Chien-Hsiung Wang,1
John Burnette,1
Adam Monahan,1
Leslie J. Kovacs,1
Angie Seegers,1
Tom Guiry,1
Bruce Dobrin,1
Jamie Stevenson,1
Eileen Horta,1
Robert Wahlberg,1
Sara Simon,1
Jason Gondek,1
Michael Stevens,1
Katherine Dorrer,1
Bill McAdams Jr.,1
Aaron Holly,1
Gerardo De La Cruz,1
Emmy Rossum,1
Celine du Tertre,1
Aillene Taylor,1
Tania McComas,1
Cottalango Loorthu,1
Krystin Johnson,1
Paul-Michel Pierre-Benoist,1
Ashaki 'Saki' Fenderson,1
Jim Choate,1
Teri Anne Kopp,1
Bradley C. Katona,1
Morgan Ratsoy,1
Mario Castillo,1
Jason McDade,1
Natalie Ungvari,1
Antony Graf,1
Richard C. Goddard,1
Ken Doyle,1
Wendy Polutanovich,1
Jason Shoubin,1
Michael Sehgal,1
Tori Davis,1

In [0]:
%sql SELECT B.primaryName, COUNT(B.originalTitle) AS Quant_filmes
FROM gold.names_titles AS B
GROUP BY B.primaryName
ORDER BY Quant_filmes DESC
LIMIT 3

primaryName,Quant_filmes
David Smith,596
Michael Smith,555
Chris Smith,513

In [0]:
%sql SELECT B.primaryName, COUNT(B.originalTitle) AS Quant_filmes
FROM gold.names_titles AS B
GROUP BY B.primaryName
ORDER BY Quant_filmes ASC
LIMIT 1

primaryName,Quant_filmes
Rolf Knudssøn,1